import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Resolve paths relative to this script
const jsonPath = path.join(__dirname, '../public/gfx/diception.json');
const outPath = path.join(__dirname, '../public/gfx/sprites.css');

const json = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));

const sheetW = json.meta.size.w;
const sheetH = json.meta.size.h;

let css = `/* Auto-generated by scripts/generate-css.js */

.sprite-icon {
    display: inline-block;
    height: 1.2em; /* Base height */
    width: auto;   /* Width derived from aspect-ratio */
    background-image: url('diception.png');
    background-repeat: no-repeat;
    vertical-align: middle; /* Align with text */
    transform: translateY(-0.1em); /* Optical centering */
    flex: none; /* Prevent stretching in flex containers */
    align-self: center; /* Prevent cross-axis stretching */
}

/* Specific icons */
`;

// Sprite families to generate CSS classes for (matched against the basename)
const CSS_PREFIXES = ['icon_', 'xbox_', 'playstation_', 'playstation4_', 'playstation5_', 'keyboard_', 'mouse_'];

for (const [name, data] of Object.entries(json.frames)) {
    // Strip folder path — frame names are now like "game/icon_zoom_in.png"
    const basename = path.basename(name);

    // Skip animation frames and anything else not used as CSS sprites
    if (!CSS_PREFIXES.some(p => basename.startsWith(p))) continue;

    // "xbox_button_color_a.png" -> "xbox-button-color-a"
    const className = basename.replace('.png', '').replace(/_/g, '-');
    const f = data.frame;

    // Calculate background-size (The size of the whole image represented as percentage of the element size)
    // If we want the frame (f.w) to fill the element (100%), the whole sheet (sheetW) must be scaled relative to it.
    // Scale = 100% corresponds to f.w
    // SheetPct = (sheetW / f.w) * 100
    const sizeX = (sheetW / f.w) * 100;
    const sizeY = (sheetH / f.h) * 100;

    // Calculate background-position
    // CSS percentage position: P = x / (SheetW - FrameW) * 100%
    const posX = f.x === 0 ? 0 : (f.x / (sheetW - f.w)) * 100;
    const posY = f.y === 0 ? 0 : (f.y / (sheetH - f.h)) * 100;

    css += `.${className} {
    background-size: ${sizeX.toFixed(4)}% ${sizeY.toFixed(4)}%;
    background-position: ${posX.toFixed(4)}% ${posY.toFixed(4)}%;
    aspect-ratio: ${f.w} / ${f.h};
}\n`;
}

try {
    fs.writeFileSync(outPath, css);
    console.log(`✓ Generated ${outPath}`);
    console.log(`  - Sheet: ${sheetW}x${sheetH}`);
} catch (e) {
    console.error('Error writing CSS:', e);
}
