"""Fill German and Spanish into steam/storepage_1106365_all.json.

Only the prose is replaced; BBCode tags, {STEAM_APP_IMAGE} references and the
&quot;/&amp; entity encoding are carried over from the English source untouched,
so the localized pages keep exactly the same layout as the English one.

The section title images stay on their English names on purpose: they are
uploaded in Steamworks as localized versions of the same asset, so Steam
serves the right language itself and falls back to English where a language
has none.

Run from the repo root, then upload the JSON in Steamworks under
Store Presence -> Localization.
"""
import json, sys

VDF = 'steam/storepage_1106365_all.json'
ABOUT = 'app[content][about]'
SHORT = 'app[content][short_description]'

# Corrections applied to the English about text before anything is translated,
# so every language stays in sync. Upload fixes the English page too.
ENGLISH_FIXES = [
    # unfinished sentence
    ("are waiting for you to.\u00a0", "are waiting for you.\u00a0"),
    # double space
    ("Or try  [b]parallel turns[/b]", "Or try [b]parallel turns[/b]"),
    # stray empty bold paragraph above the campaign blurb
    ("[p][b] [/b] [/p]", ""),
]

# One dict per paragraph of the English about text, keyed by Steam's own
# language name. Adding a language means adding its key to each of these, to
# SHORT_TEXT and to every SYSREQS entry; anything less and it is skipped.
ABOUT_PARTS = [
    {
        'english': '[b]Diception[/b] is a fast, minimalistic conquest game. Inspired by classics like [i]Risk[/i] and [i]DiceWars[/i], it features quick turn-based matches, an extensive campaign, a built-in editor, and local multiplayer for up to 8 players. By replacing the classic isometric view with an optimized [b]2D Grid View[/b], the game offers seamless Mouse, Keyboard, and Gamepad support for a lightning-fast experience.',
        'brazilian': '[b]Diception[/b] é um jogo de conquista rápido e minimalista. Inspirado em clássicos como [i]Risk[/i] e [i]DiceWars[/i], traz partidas curtas por turnos, uma campanha extensa, um editor integrado e multijogador local para até 8 jogadores. No lugar da clássica visão isométrica, usa uma [b]visão em grade 2D[/b] otimizada, com suporte fluido a mouse, teclado e controle, e a velocidade que isso permite.',
        'bulgarian': '[b]Diception[/b] е бърза, минималистична игра за завладяване. Вдъхновена от класики като [i]Risk[/i] и [i]DiceWars[/i], тя предлага кратки партии на ходове, обширна кампания, вграден редактор и локална игра за до 8 играчи. Вместо класическия изометричен изглед използва оптимизиран [b]2D изглед с мрежа[/b], с плавна поддръжка на мишка, клавиатура и контролер, и съответното темпо.',
        'czech': '[b]Diception[/b] je rychlá, minimalistická dobyvatelská hra. Inspirovaná klasikami jako [i]Risk[/i] a [i]DiceWars[/i] nabízí krátké tahové partie, rozsáhlou kampaň, vestavěný editor a místní hru až pro 8 hráčů. Místo klasického izometrického pohledu používá optimalizovaný [b]2D pohled na mřížku[/b], s plynulou podporou myši, klávesnice a gamepadu, a tomu odpovídajícím tempem.',
        'danish': '[b]Diception[/b] er et hurtigt, minimalistisk erobringsspil. Inspireret af klassikere som [i]Risk[/i] og [i]DiceWars[/i] byder det på korte turbaserede partier, en omfattende kampagne, en indbygget editor og lokal flerspiller for op til 8 spillere. I stedet for det klassiske isometriske billede bruger det en optimeret [b]2D-gittervisning[/b] med glidende understøttelse af mus, tastatur og controller, og det tempo der følger med.',
        'dutch': '[b]Diception[/b] is een snel, minimalistisch veroveringsspel. Geïnspireerd op klassiekers als [i]Risk[/i] en [i]DiceWars[/i] biedt het korte beurtgebaseerde partijen, een uitgebreide campagne, een ingebouwde editor en lokale multiplayer voor maximaal 8 spelers. In plaats van het klassieke isometrische beeld gebruikt het een geoptimaliseerde [b]2D-rasterweergave[/b], met vloeiende ondersteuning voor muis, toetsenbord en controller, en het tempo dat daarbij hoort.',
        'finnish': '[b]Diception[/b] on nopea ja pelkistetty valloituspeli. [i]Risk[/i]in ja [i]DiceWars[/i]in kaltaisista klassikoista ammentava peli tarjoaa lyhyitä vuoropohjaisia otteluita, laajan kampanjan, sisäänrakennetun editorin ja paikallisen moninpelin jopa 8 pelaajalle. Perinteisen isometrisen näkymän sijaan käytössä on optimoitu [b]2D-ruudukkonäkymä[/b], joka tukee saumattomasti hiirtä, näppäimistöä ja ohjainta, ja kulkee sen mukaisella vauhdilla.',
        'french': "[b]Diception[/b] est un jeu de conquête rapide et minimaliste. Inspiré de classiques comme [i]Risk[/i] et [i]DiceWars[/i], il propose des parties au tour par tour rapides, une campagne étoffée, un éditeur intégré et du multijoueur local jusqu'à 8 joueurs. En remplaçant la vue isométrique classique par une [b]vue en grille 2D[/b] optimisée, le jeu offre une prise en main fluide à la souris, au clavier et à la manette, pour une expérience ultra-rapide.",
        'german': '[b]Diception[/b] ist ein schnelles, minimalistisches Eroberungsspiel. Inspiriert von Klassikern wie [i]Risiko[/i] und [i]DiceWars[/i] bietet es kurze rundenbasierte Partien, eine umfangreiche Kampagne, einen eingebauten Editor und lokalen Mehrspieler für bis zu 8 Spieler. Statt der klassischen isometrischen Ansicht nutzt Diception eine optimierte [b]2D-Rasteransicht[/b], mit durchgängiger Unterstützung für Maus, Tastatur und Gamepad und entsprechend hohem Tempo.',
        'greek': '[b]Το Diception[/b] είναι ένα γρήγορο, μινιμαλιστικό παιχνίδι κατάκτησης. Εμπνευσμένο από κλασικά όπως το [i]Risk[/i] και το [i]DiceWars[/i], προσφέρει σύντομες παρτίδες με σειρές, μια εκτενή εκστρατεία, ενσωματωμένο επεξεργαστή και τοπικό παιχνίδι για έως 8 παίκτες. Αντί για την κλασική ισομετρική όψη χρησιμοποιεί μια βελτιστοποιημένη [b]όψη πλέγματος 2D[/b], με απρόσκοπτη υποστήριξη ποντικιού, πληκτρολογίου και χειριστηρίου, και την ταχύτητα που αυτό επιτρέπει.',
        'hungarian': '[b]Diception[/b] egy gyors, letisztult hódítós játék. Az olyan klasszikusokból merít, mint a [i]Risk[/i] és a [i]DiceWars[/i], és rövid körökre osztott meccseket, terjedelmes kampányt, beépített szerkesztőt és akár 8 fős helyi többjátékos módot kínál. A megszokott izometrikus nézet helyett optimalizált [b]2D rácsnézetet[/b] használ, egérrel, billentyűzettel és kontrollerrel egyaránt gördülékenyen, a hozzá tartozó tempóval.',
        'indonesian': '[b]Diception[/b] adalah permainan penaklukan yang cepat dan sederhana. Terinspirasi karya klasik seperti [i]Risk[/i] dan [i]DiceWars[/i], permainan ini menyuguhkan pertandingan bergiliran yang singkat, kampanye yang luas, penyunting bawaan, dan main bersama di satu perangkat hingga 8 pemain. Alih-alih tampilan isometrik yang biasa, ia memakai [b]tampilan grid 2D[/b] yang dioptimalkan, dengan dukungan mulus untuk mouse, keyboard, dan gamepad, serta kecepatan yang menyertainya.',
        'italian': "[b]Diception[/b] è un gioco di conquista rapido e minimalista. Ispirato a classici come [i]Risk[/i] e [i]DiceWars[/i], offre partite a turni veloci, una campagna ricca, un editor integrato e multigiocatore locale fino a 8 giocatori. Sostituendo la classica vista isometrica con una [b]vista a griglia 2D[/b] ottimizzata, il gioco garantisce un supporto fluido per mouse, tastiera e controller, per un'esperienza fulminea.",
        'japanese': '[b]Diception[/b] は、テンポの速いミニマルな陣取りゲームです。[i]Risk[/i] や [i]DiceWars[/i] といった古典に着想を得て、短いターン制の対戦、充実したキャンペーン、内蔵エディター、最大8人のローカル対戦を収録。従来のアイソメトリック表示ではなく最適化された [b]2Dグリッド表示[/b] を採用し、マウス・キーボード・ゲームパッドをなめらかにサポートします。',
        'koreana': '[b]Diception[/b]은 빠르고 군더더기 없는 정복 게임입니다. [i]Risk[/i]와 [i]DiceWars[/i] 같은 고전에서 영감을 받아 짧은 턴제 대전, 풍성한 캠페인, 내장 에디터, 최대 8인 로컬 멀티플레이를 담았습니다. 전통적인 아이소메트릭 시점 대신 최적화된 [b]2D 그리드 뷰[/b]를 사용해 마우스와 키보드, 게임패드를 매끄럽게 지원하며 그만큼 빠릅니다.',
        'latam': '[b]Diception[/b] es un juego de conquista rápido y minimalista. Inspirado en clásicos como [i]Risk[/i] y [i]DiceWars[/i], ofrece partidas por turnos ágiles, una campaña extensa, un editor integrado y multijugador local para hasta 8 jugadores. En lugar de la clásica vista isométrica utiliza una [b]vista de cuadrícula 2D[/b] optimizada, con soporte fluido para mouse, teclado y control, y la velocidad que eso permite.',
        'malay': '[b]Diception[/b] ialah permainan penaklukan yang pantas dan ringkas. Diilhamkan oleh karya klasik seperti [i]Risk[/i] dan [i]DiceWars[/i], ia menawarkan perlawanan bergilir yang singkat, kempen yang luas, penyunting terbina dalam, dan permainan bersama pada satu peranti untuk sehingga 8 pemain. Selain paparan isometrik yang biasa, ia menggunakan [b]paparan grid 2D[/b] yang dioptimumkan, dengan sokongan lancar untuk tetikus, papan kekunci dan gamepad, serta kepantasan yang datang dengannya.',
        'norwegian': '[b]Diception[/b] er et raskt, minimalistisk erobringsspill. Inspirert av klassikere som [i]Risk[/i] og [i]DiceWars[/i] byr det på korte turbaserte partier, en omfattende kampanje, en innebygd editor og lokal flerspiller for opptil 8 spillere. I stedet for det klassiske isometriske bildet bruker det en optimalisert [b]2D-rutenettvisning[/b], med sømløs støtte for mus, tastatur og håndkontroll, og tempoet som følger med.',
        'polish': '[b]Diception[/b] to szybka, minimalistyczna gra o podboju. Zainspirowana klasykami pokroju [i]Risk[/i] i [i]DiceWars[/i] oferuje krótkie partie turowe, rozbudowaną kampanię, wbudowany edytor i grę lokalną nawet dla 8 osób. Zamiast klasycznego widoku izometrycznego korzysta z zoptymalizowanego [b]widoku siatki 2D[/b], z płynną obsługą myszy, klawiatury i pada, a więc i z odpowiednim tempem.',
        'portuguese': '[b]Diception[/b] é um jogo de conquista rápido e minimalista. Inspirado em clássicos como [i]Risk[/i] e [i]DiceWars[/i], traz partidas curtas por turnos, uma campanha extensa, um editor integrado e multijogador local até 8 jogadores. Em vez da clássica vista isométrica, usa uma [b]vista em grelha 2D[/b] otimizada, com suporte fluido a rato, teclado e comando, e a velocidade que isso permite.',
        'romanian': '[b]Diception[/b] este un joc de cucerire rapid și minimalist. Inspirat din clasice precum [i]Risk[/i] și [i]DiceWars[/i], oferă partide scurte pe ture, o campanie amplă, un editor integrat și joc local pentru până la 8 jucători. În locul clasicei vederi izometrice folosește o [b]vedere pe grilă 2D[/b] optimizată, cu suport fluid pentru mouse, tastatură și controler, și viteza pe care o permite asta.',
        'russian': '[b]Diception[/b] — быстрая минималистичная игра о завоевании. Вдохновлённая классикой вроде [i]Risk[/i] и [i]DiceWars[/i], она предлагает короткие пошаговые партии, большую кампанию, встроенный редактор и локальную игру до 8 человек. Вместо классического изометрического вида здесь оптимизированный [b]2D-вид сеткой[/b], с полноценной поддержкой мыши, клавиатуры и геймпада — и соответствующей скоростью.',
        'schinese': '[b]Diception[/b] 是一款快节奏、极简风格的征服游戏。灵感来自 [i]Risk[/i] 和 [i]DiceWars[/i] 等经典作品，提供简短的回合制对局、丰富的战役、内置编辑器，以及最多 8 人的本地多人游戏。它没有采用传统的等距视角，而是使用经过优化的 [b]2D 网格视图[/b]，全面支持鼠标、键盘和手柄，带来相应的高速体验。',
        'spanish': '[b]Diception[/b] es un juego de conquista rápido y minimalista. Inspirado en clásicos como [i]Risk[/i] y [i]DiceWars[/i], ofrece partidas por turnos ágiles, una campaña extensa, un editor integrado y multijugador local para hasta 8 jugadores. En lugar de la clásica vista isométrica utiliza una [b]vista de rejilla 2D[/b] optimizada, con soporte fluido para ratón, teclado y mando, y la velocidad que eso permite.',
        'swedish': '[b]Diception[/b] är ett snabbt, minimalistiskt erövringsspel. Inspirerat av klassiker som [i]Risk[/i] och [i]DiceWars[/i] bjuder det på korta turordningsbaserade partier, en omfattande kampanj, en inbyggd editor och lokalt flerspelarläge för upp till 8 spelare. I stället för den klassiska isometriska vyn används en optimerad [b]2D-rutnätsvy[/b], med sömlöst stöd för mus, tangentbord och handkontroll, och tempot som följer med.',
        'tchinese': '[b]Diception[/b] 是一款節奏明快、極簡風格的征服遊戲。靈感來自 [i]Risk[/i] 和 [i]DiceWars[/i] 等經典作品，提供簡短的回合制對局、豐富的戰役、內建編輯器，以及最多 8 人的本機多人遊戲。它沒有採用傳統的等距視角，而是使用經過最佳化的 [b]2D 網格視圖[/b]，全面支援滑鼠、鍵盤和手把，帶來相應的高速體驗。',
        'turkish': '[b]Diception[/b] hızlı ve sade bir fetih oyunu. [i]Risk[/i] ve [i]DiceWars[/i] gibi klasiklerden ilham alan oyun, kısa sıra tabanlı maçlar, geniş bir kampanya, dahili bir düzenleyici ve 8 oyuncuya kadar yerel çok oyunculu mod sunuyor. Klasik izometrik görünüm yerine optimize edilmiş bir [b]2B ızgara görünümü[/b] kullanıyor; fare, klavye ve oyun kumandası desteği kusursuz, hız da buna göre.',
        'ukrainian': '[b]Diception[/b] — швидка мінімалістична гра про завоювання. Натхненна класикою на кшталт [i]Risk[/i] і [i]DiceWars[/i], вона пропонує короткі покрокові партії, велику кампанію, вбудований редактор і локальну гру до 8 осіб. Замість класичного ізометричного вигляду тут оптимізований [b]2D-вигляд сіткою[/b], з повноцінною підтримкою миші, клавіатури й геймпада — і відповідною швидкістю.',
        'vietnamese': '[b]Diception[/b] là một trò chơi chinh phục nhanh và tối giản. Lấy cảm hứng từ những tựa game kinh điển như [i]Risk[/i] và [i]DiceWars[/i], trò chơi mang đến các ván đấu theo lượt ngắn gọn, một chiến dịch đồ sộ, trình sửa tích hợp và chơi chung trên một máy cho tối đa 8 người. Thay cho góc nhìn đẳng cự quen thuộc, trò chơi dùng [b]góc nhìn lưới 2D[/b] đã tối ưu, hỗ trợ mượt mà chuột, bàn phím và tay cầm, cùng tốc độ tương xứng.',
    },
    {
        'english': '[h2][b]Key Features:[/b][/h2]',
        'brazilian': '[h2][b]Destaques:[/b][/h2]',
        'bulgarian': '[h2][b]Основни особености:[/b][/h2]',
        'czech': '[h2][b]Hlavní vlastnosti:[/b][/h2]',
        'danish': '[h2][b]Vigtigste funktioner:[/b][/h2]',
        'dutch': '[h2][b]Belangrijkste kenmerken:[/b][/h2]',
        'finnish': '[h2][b]Tärkeimmät ominaisuudet:[/b][/h2]',
        'french': '[h2][b]Points forts :[/b][/h2]',
        'german': '[h2][b]Hauptmerkmale:[/b][/h2]',
        'greek': '[h2][b]Βασικά χαρακτηριστικά:[/b][/h2]',
        'hungarian': '[h2][b]Főbb jellemzők:[/b][/h2]',
        'indonesian': '[h2][b]Fitur utama:[/b][/h2]',
        'italian': '[h2][b]Caratteristiche principali:[/b][/h2]',
        'japanese': '[h2][b]主な特徴：[/b][/h2]',
        'koreana': '[h2][b]주요 특징:[/b][/h2]',
        'latam': '[h2][b]Características principales:[/b][/h2]',
        'malay': '[h2][b]Ciri utama:[/b][/h2]',
        'norwegian': '[h2][b]Viktigste funksjoner:[/b][/h2]',
        'polish': '[h2][b]Najważniejsze cechy:[/b][/h2]',
        'portuguese': '[h2][b]Destaques:[/b][/h2]',
        'romanian': '[h2][b]Caracteristici principale:[/b][/h2]',
        'russian': '[h2][b]Ключевые особенности:[/b][/h2]',
        'schinese': '[h2][b]主要特色：[/b][/h2]',
        'spanish': '[h2][b]Características principales:[/b][/h2]',
        'swedish': '[h2][b]Viktigaste funktionerna:[/b][/h2]',
        'tchinese': '[h2][b]主要特色：[/b][/h2]',
        'turkish': '[h2][b]Öne çıkan özellikler:[/b][/h2]',
        'ukrainian': '[h2][b]Ключові особливості:[/b][/h2]',
        'vietnamese': '[h2][b]Điểm nổi bật:[/b][/h2]',
    },
    {
        'english': 'Diception uses a clean 2D matrix with 4-way connections. This enables lightning-fast [b]WASD and D-Pad controls[/b], allowing for rapid-fire gameplay without sacrificing strategic depth.',
        'brazilian': 'Diception usa uma matriz 2D limpa com conexões nas quatro direções. Isso deixa os [b]controles WASD e do direcional[/b] rapidíssimos: ritmo alto, sem abrir mão da profundidade estratégica.',
        'bulgarian': 'Diception използва чиста 2D матрица с връзки в четири посоки. Затова [b]управлението с WASD и кръстатия бутон[/b] е светкавично: високо темпо, без да се жертва стратегическата дълбочина.',
        'czech': 'Diception používá čistou 2D matici se spoji ve čtyřech směrech. Díky tomu je [b]ovládání pomocí WASD a křížového ovladače[/b] bleskové: vysoké tempo, aniž by tím trpěla strategická hloubka.',
        'danish': 'Diception bruger en ren 2D-matrix med forbindelser i fire retninger. Det gør [b]WASD- og D-pad-styring[/b] lynhurtig: højt tempo uden at gå på kompromis med den strategiske dybde.',
        'dutch': 'Diception gebruikt een strakke 2D-matrix met verbindingen in vier richtingen. Daardoor zijn [b]WASD- en D-padbesturing[/b] razendsnel: hoog tempo, zonder in te leveren op strategische diepgang.',
        'finnish': 'Diception käyttää selkeää 2D-matriisia, jossa ruudut liittyvät neljään suuntaan. Siksi [b]WASD- ja ristiohjaimen hallinta[/b] on salamannopeaa: kova vauhti ilman että strateginen syvyys kärsii.',
        'french': 'Diception utilise une matrice 2D épurée avec des connexions dans quatre directions. Cela permet des [b]commandes WASD et croix directionnelle[/b] fulgurantes : un rythme soutenu, sans sacrifier la profondeur stratégique.',
        'german': 'Diception nutzt eine klare 2D-Matrix mit Verbindungen in vier Richtungen. Das ermöglicht blitzschnelle Steuerung per [b]WASD und Steuerkreuz[/b]: hohes Tempo, ohne strategische Tiefe zu opfern.',
        'greek': 'Το Diception χρησιμοποιεί έναν καθαρό πίνακα 2D με συνδέσεις προς τέσσερις κατευθύνσεις. Έτσι ο [b]χειρισμός με WASD και σταυρό[/b] γίνεται αστραπιαίος: γρήγορος ρυθμός, χωρίς να θυσιάζεται το στρατηγικό βάθος.',
        'hungarian': 'A Diception letisztult 2D mátrixot használ, négy irányú kapcsolatokkal. Ettől villámgyors a [b]WASD és az iránygomb kezelése[/b]: pörgős játékmenet a stratégiai mélység feláldozása nélkül.',
        'indonesian': 'Diception memakai matriks 2D yang bersih dengan sambungan ke empat arah. Berkat itu [b]kendali WASD dan D-pad[/b] terasa sangat cepat: tempo tinggi tanpa mengorbankan kedalaman strategi.',
        'italian': 'Diception usa una matrice 2D pulita con collegamenti nelle quattro direzioni. Questo rende i [b]comandi WASD e con la croce direzionale[/b] rapidissimi: ritmo altissimo, senza rinunciare alla profondità strategica.',
        'japanese': 'Diception は四方向につながるシンプルな2Dマトリクスを使います。そのおかげで [b]WASDと十字キーの操作[/b] が非常に速く、戦略の深さを損なわずにテンポよく遊べます。',
        'koreana': 'Diception은 사방으로 이어지는 깔끔한 2D 격자를 사용합니다. 덕분에 [b]WASD와 방향키 조작[/b]이 매우 빠르며, 전략적 깊이를 포기하지 않고도 경쾌하게 플레이할 수 있습니다.',
        'latam': 'Diception utiliza una matriz 2D limpia con conexiones en cuatro direcciones. Eso permite un control rapidísimo con [b]WASD y la cruceta[/b]: partidas veloces sin renunciar a la profundidad estratégica.',
        'malay': 'Diception menggunakan matriks 2D yang kemas dengan sambungan ke empat arah. Justeru [b]kawalan WASD dan D-pad[/b] terasa amat pantas: tempo tinggi tanpa mengorbankan kedalaman strategi.',
        'norwegian': 'Diception bruker en ren 2D-matrise med forbindelser i fire retninger. Det gjør [b]WASD- og D-pad-styring[/b] lynrask: høyt tempo uten å ofre strategisk dybde.',
        'polish': 'Diception korzysta z czystej matrycy 2D z połączeniami w czterech kierunkach. Dzięki temu [b]sterowanie WASD i krzyżakiem[/b] jest błyskawiczne: wysokie tempo bez rezygnacji z głębi strategicznej.',
        'portuguese': 'O Diception usa uma matriz 2D limpa com ligações nas quatro direções. Isso torna os [b]comandos WASD e do direcional[/b] rapidíssimos: ritmo alto, sem abdicar da profundidade estratégica.',
        'romanian': 'Diception folosește o matrice 2D curată, cu legături în patru direcții. Asta face ca [b]comenzile WASD și de pe cruce[/b] să fie fulgerătoare: ritm alert, fără să sacrifice profunzimea strategică.',
        'russian': 'Diception использует чистую 2D-матрицу со связями в четырёх направлениях. Это даёт молниеносное [b]управление на WASD и крестовине[/b]: высокий темп без потери стратегической глубины.',
        'schinese': 'Diception 采用清爽的 2D 矩阵，四方向相连。这让 [b]WASD 和方向键操作[/b] 极为迅捷——速度快，却不牺牲策略深度。',
        'spanish': 'Diception utiliza una matriz 2D limpia con conexiones en cuatro direcciones. Eso permite un control rapidísimo con [b]WASD y cruceta[/b]: partidas veloces sin renunciar a la profundidad estratégica.',
        'swedish': 'Diception använder en ren 2D-matris med förbindelser i fyra riktningar. Det gör [b]WASD- och styrkorsstyrning[/b] blixtsnabb: högt tempo utan att offra det strategiska djupet.',
        'tchinese': 'Diception 採用清爽的 2D 矩陣，四方向相連。這讓 [b]WASD 和方向鍵操作[/b] 極為迅捷——速度快，卻不犧牲策略深度。',
        'turkish': 'Diception, dört yönde bağlantısı olan sade bir 2B matris kullanır. Bu sayede [b]WASD ve yön tuşu kontrolleri[/b] son derece hızlıdır: stratejik derinlikten ödün vermeden yüksek tempo.',
        'ukrainian': "Diception використовує чисту 2D-матрицю зі зв'язками в чотирьох напрямках. Завдяки цьому [b]керування на WASD і хрестовині[/b] блискавичне: високий темп без утрати стратегічної глибини.",
        'vietnamese': 'Diception dùng một ma trận 2D gọn gàng, nối theo bốn hướng. Nhờ vậy [b]điều khiển bằng WASD và D-pad[/b] cực nhanh: nhịp độ cao mà không đánh đổi chiều sâu chiến thuật.',
    },
    {
        'english': "Battle up to 8 players in local multiplayer (Gamepads supported). Thanks to [b]Steam Remote Play Together[/b], your friends can join the fun online even if they don't own the game!",
        'brazilian': 'Enfrente até 8 jogadores no multijogador local (com suporte a controles). Graças ao [b]Steam Remote Play Together[/b], seus amigos podem entrar online mesmo sem ter o jogo!',
        'bulgarian': 'Премери сили с до 8 играчи в локална игра (контролерите се поддържат). Благодарение на [b]Steam Remote Play Together[/b] приятелите ти могат да се включат онлайн дори ако нямат играта!',
        'czech': 'Utkej se až s 8 hráči v místní hře (gamepady podporovány). Díky [b]Steam Remote Play Together[/b] se kamarádi můžou přidat online, i když hru nevlastní!',
        'danish': 'Tag kampen op mod op til 8 spillere i lokal flerspiller (controllere understøttes). Takket være [b]Steam Remote Play Together[/b] kan dine venner være med online, selv om de ikke ejer spillet!',
        'dutch': 'Neem het in lokale multiplayer op tegen maximaal 8 spelers (controllers worden ondersteund). Dankzij [b]Steam Remote Play Together[/b] kunnen je vrienden online meedoen, ook als ze het spel niet hebben!',
        'finnish': 'Ota mittaa jopa 8 pelaajasta paikallisessa moninpelissä (ohjaimet tuettuina). [b]Steam Remote Play Togetherin[/b] ansiosta kaverisi pääsevät mukaan verkossa, vaikka peliä ei olisi heillä!',
        'french': "Affrontez jusqu'à 8 joueurs en multijoueur local (manettes prises en charge). Grâce à [b]Steam Remote Play Together[/b], vos amis peuvent vous rejoindre en ligne même s'ils ne possèdent pas le jeu !",
        'german': 'Tritt im lokalen Mehrspieler gegen bis zu 8 Spieler an (Gamepads werden unterstützt). Dank [b]Steam Remote Play Together[/b] können deine Freunde online mitspielen, auch wenn sie das Spiel gar nicht besitzen!',
        'greek': 'Αντιμετώπισε έως 8 παίκτες σε τοπικό παιχνίδι (υποστηρίζονται χειριστήρια). Χάρη στο [b]Steam Remote Play Together[/b] οι φίλοι σου μπορούν να μπουν διαδικτυακά, ακόμη κι αν δεν έχουν το παιχνίδι!',
        'hungarian': 'Mérkőzz meg akár 8 játékossal helyi többjátékos módban (kontrollerek támogatottak). A [b]Steam Remote Play Together[/b] jóvoltából a barátaid online is csatlakozhatnak, még akkor is, ha nincs meg nekik a játék!',
        'indonesian': 'Hadapi hingga 8 pemain dalam permainan bersama di satu perangkat (gamepad didukung). Berkat [b]Steam Remote Play Together[/b], temanmu bisa ikut bermain daring meski tidak punya permainannya!',
        'italian': 'Sfida fino a 8 giocatori in multigiocatore locale (controller supportati). Grazie a [b]Steam Remote Play Together[/b] i tuoi amici possono unirsi online anche se non possiedono il gioco!',
        'japanese': 'ローカル対戦で最大8人と戦えます（ゲームパッド対応）。[b]Steam Remote Play Together[/b] を使えば、ゲームを持っていない友達もオンラインで参加できます！',
        'koreana': '로컬 멀티플레이로 최대 8명과 겨뤄 보세요(게임패드 지원). [b]Steam Remote Play Together[/b] 덕분에 게임이 없는 친구도 온라인으로 함께할 수 있습니다!',
        'latam': 'Enfréntate a hasta 8 jugadores en multijugador local (con soporte para controles). Gracias a [b]Steam Remote Play Together[/b], tus amigos pueden unirse en línea aunque no tengan el juego.',
        'malay': 'Tempuh sehingga 8 pemain dalam permainan bersama pada satu peranti (gamepad disokong). Berkat [b]Steam Remote Play Together[/b], rakan anda boleh menyertai dalam talian walaupun tidak memiliki permainan ini!',
        'norwegian': 'Møt opptil 8 spillere i lokal flerspiller (håndkontroller støttes). Takket være [b]Steam Remote Play Together[/b] kan vennene dine bli med på nett selv om de ikke eier spillet!',
        'polish': 'Zmierz się nawet z 8 graczami w grze lokalnej (pady obsługiwane). Dzięki [b]Steam Remote Play Together[/b] znajomi mogą dołączyć przez internet, nawet jeśli nie mają gry!',
        'portuguese': 'Enfrenta até 8 jogadores em multijogador local (com suporte a comandos). Graças ao [b]Steam Remote Play Together[/b], os teus amigos podem juntar-se online mesmo sem terem o jogo!',
        'romanian': 'Înfruntă până la 8 jucători în joc local (controlerele sunt acceptate). Datorită [b]Steam Remote Play Together[/b], prietenii tăi se pot alătura online chiar dacă nu au jocul!',
        'russian': 'Сражайтесь с семью соперниками в локальной игре (геймпады поддерживаются). Благодаря [b]Steam Remote Play Together[/b] друзья могут присоединиться онлайн, даже если игры у них нет!',
        'schinese': '在本地多人模式中与最多 8 名玩家对战（支持手柄）。借助 [b]Steam Remote Play Together[/b]，你的好友即使没有本作也能在线加入！',
        'spanish': 'Enfréntate a hasta 8 jugadores en multijugador local (con soporte para mandos). Gracias a [b]Steam Remote Play Together[/b], tus amigos pueden unirse en línea aunque no tengan el juego.',
        'swedish': 'Möt upp till 8 spelare i lokalt flerspelarläge (handkontroller stöds). Tack vare [b]Steam Remote Play Together[/b] kan dina vänner vara med online även om de inte äger spelet!',
        'tchinese': '在本機多人模式中與最多 8 名玩家對戰（支援手把）。藉由 [b]Steam Remote Play Together[/b]，你的好友即使沒有本作也能在線上加入！',
        'turkish': 'Yerel çok oyunculu modda 8 oyuncuya kadar karşı karşıya gel (oyun kumandaları destekleniyor). [b]Steam Remote Play Together[/b] sayesinde arkadaşların oyuna sahip olmasa bile çevrimiçi katılabilir!',
        'ukrainian': 'Позмагайся з сімома суперниками в локальній грі (геймпади підтримуються). Завдяки [b]Steam Remote Play Together[/b] друзі можуть приєднатися онлайн, навіть якщо гри в них немає!',
        'vietnamese': 'Đối đầu với tối đa 8 người chơi khi chơi chung trên một máy (hỗ trợ tay cầm). Nhờ [b]Steam Remote Play Together[/b], bạn bè có thể tham gia trực tuyến ngay cả khi họ không có trò chơi!',
    },
    {
        'english': 'Choose from 3 different speed modes. Whether you want to analyze every move or &quot;blitz&quot; through territories in milliseconds, the choice is yours.',
        'brazilian': 'Escolha entre 3 modos de velocidade. Quer analisar cada jogada ou atravessar os territórios num &quot;blitz&quot; de milissegundos? A escolha é sua.',
        'bulgarian': 'Избери един от 3 режима на скорост. Дали ще обмисляш всеки ход, или ще прелетиш през териториите с &quot;блиц&quot; за милисекунди, изборът е твой.',
        'czech': 'Vyber si ze 3 režimů rychlosti. Ať už chceš promýšlet každý tah, nebo se přes území prohnat &quot;bleskovkou&quot; během milisekund, je to na tobě.',
        'danish': 'Vælg mellem 3 hastighedstilstande. Uanset om du vil tænke hvert træk igennem eller &quot;lynkrige&quot; gennem områderne på millisekunder, er valget dit.',
        'dutch': 'Kies uit 3 snelheidsmodi. Of je nu elke zet wilt uitdenken of in milliseconden door de gebieden wilt &quot;blitzen&quot;: jij bepaalt.',
        'finnish': 'Valitse kolmesta nopeustilasta. Halusitpa puntaroida jokaisen siirron tai &quot;salamasotia&quot; alueiden läpi millisekunneissa, valinta on sinun.',
        'french': "Choisissez parmi 3 modes de vitesse. Que vous vouliez analyser chaque coup ou traverser les territoires en &quot;blitz&quot; en quelques millisecondes, c'est vous qui décidez.",
        'german': 'Wähle zwischen 3 Geschwindigkeitsmodi. Ob du jeden Zug in Ruhe durchdenken oder in Millisekunden durch die Gebiete &quot;blitzen&quot; willst: du entscheidest.',
        'greek': 'Διάλεξε ανάμεσα σε 3 ταχύτητες. Είτε θέλεις να ζυγίζεις κάθε κίνηση είτε να περνάς μέσα από τις περιοχές σαν &quot;κεραυνός&quot; σε χιλιοστά του δευτερολέπτου, η επιλογή είναι δική σου.',
        'hungarian': 'Válassz a 3 sebességmód közül. Akár minden lépést végig akarsz gondolni, akár ezredmásodpercek alatt &quot;villámháborúzol&quot; végig a területeken, a döntés a tiéd.',
        'indonesian': 'Pilih satu dari 3 mode kecepatan. Mau menimbang setiap langkah atau melesat melewati wilayah dengan &quot;blitz&quot; dalam hitungan milidetik, semuanya terserah kamu.',
        'italian': 'Scegli tra 3 modalità di velocità. Che tu voglia analizzare ogni mossa o attraversare i territori in &quot;blitz&quot; nel giro di millisecondi, la scelta è tua.',
        'japanese': '3種類のスピードモードから選べます。一手ずつじっくり考えるのも、ミリ秒単位で領地を &quot;電撃戦&quot; で駆け抜けるのも自由です。',
        'koreana': '3가지 속도 모드 중에서 고르세요. 한 수 한 수 꼼꼼히 따져 보든, 밀리초 단위로 영토를 &quot;전격전&quot;처럼 훑고 지나가든 선택은 당신의 몫입니다.',
        'latam': 'Elige entre 3 modos de velocidad. Ya sea que quieras analizar cada movimiento o hacer un &quot;blitz&quot; por los territorios en milisegundos, tú decides.',
        'malay': 'Pilih satu daripada 3 mod kelajuan. Sama ada anda mahu menimbang setiap langkah atau meredah wilayah dengan &quot;blitz&quot; dalam milisaat, pilihan di tangan anda.',
        'norwegian': 'Velg mellom 3 hastighetsmoduser. Om du vil tenke gjennom hvert trekk eller &quot;lynkrige&quot; gjennom områdene på millisekunder, er valget ditt.',
        'polish': 'Wybierz jeden z 3 trybów szybkości. Chcesz analizować każdy ruch albo przelecieć przez terytoria &quot;blitzem&quot; w kilka milisekund? Wybór należy do ciebie.',
        'portuguese': 'Escolhe entre 3 modos de velocidade. Queres analisar cada jogada ou atravessar os territórios num &quot;blitz&quot; de milissegundos? A escolha é tua.',
        'romanian': 'Alege dintre 3 moduri de viteză. Fie că vrei să analizezi fiecare mutare, fie să treci prin teritorii ca un &quot;blitz&quot; în milisecunde, alegerea îți aparține.',
        'russian': 'Выберите один из 3 режимов скорости. Хотите обдумывать каждый ход или проноситься по территориям &quot;блицем&quot; за миллисекунды — решать вам.',
        'schinese': '从 3 种速度模式中选择。无论你想细细推敲每一步，还是在毫秒之间“闪击”各处领地，都由你决定。',
        'spanish': 'Elige entre 3 modos de velocidad. Tanto si quieres analizar cada movimiento como hacer un &quot;blitz&quot; por los territorios en milisegundos, tú decides.',
        'swedish': 'Välj mellan 3 hastighetslägen. Vare sig du vill tänka igenom varje drag eller &quot;blixtkriga&quot; genom områdena på millisekunder är valet ditt.',
        'tchinese': '從 3 種速度模式中選擇。無論你想細細推敲每一步，還是在毫秒之間「閃擊」各處領地，都由你決定。',
        'turkish': '3 hız modundan birini seç. İster her hamleyi tek tek düşün, ister milisaniyeler içinde bölgeleri &quot;yıldırım hızıyla&quot; geç, karar senin.',
        'ukrainian': 'Обери один із 3 режимів швидкості. Хочеш обдумувати кожен хід чи проноситися територіями &quot;бліцем&quot; за мілісекунди — вирішувати тобі.',
        'vietnamese': 'Chọn một trong 3 chế độ tốc độ. Dù bạn muốn cân nhắc từng nước đi hay lướt qua các lãnh thổ theo kiểu &quot;chớp nhoáng&quot; trong vài mili giây, lựa chọn là của bạn.',
    },
    {
        'english': 'Why settle for six sides? Or try [b]parallel turns[/b] for maximum chaos. Adjust win conditions, start settings and supply rules to create your own unique way to play.\xa0',
        'brazilian': 'Por que parar em seis faces? Ou experimente [b]turnos paralelos[/b] para o caos total. Ajuste condições de vitória, regras de início e de reforço e monte o seu próprio jeito de jogar. ',
        'bulgarian': 'Защо да спираме на шест страни? Или пробвай [b]паралелните ходове[/b] за пълен хаос. Настрой условията за победа, правилата за начало и за подкрепления и си създай собствен начин на игра. ',
        'czech': 'Proč zůstávat u šesti stěn? Nebo zkus [b]paralelní tahy[/b] pro maximální chaos. Uprav podmínky vítězství, pravidla startu a posil a poskládej si vlastní způsob hraní. ',
        'danish': 'Hvorfor nøjes med seks sider? Eller prøv [b]parallelle ture[/b] for maksimalt kaos. Justér sejrsbetingelser, startregler og forstærkningsregler, og byg din helt egen måde at spille på. ',
        'dutch': 'Waarom stoppen bij zes zijden? Of probeer [b]parallelle beurten[/b] voor maximale chaos. Pas winvoorwaarden, startregels en aanvoerregels aan en bouw je eigen manier van spelen. ',
        'finnish': 'Miksi tyytyä kuuteen sivuun? Tai kokeile [b]rinnakkaisia vuoroja[/b] äärimmäisen kaaoksen vuoksi. Säädä voittoehtoja, aloitusasetuksia ja vahvistussääntöjä ja rakenna oma tapasi pelata. ',
        'french': 'Pourquoi se contenter de six faces ? Ou essayez les [b]tours parallèles[/b] pour un chaos maximal. Ajustez les conditions de victoire, les règles de départ et de renfort pour créer votre propre façon de jouer.\xa0',
        'german': 'Warum bei sechs Seiten aufhören? Oder probiere [b]parallele Züge[/b] für maximales Chaos. Passe Siegbedingungen, Startregeln und Nachschubregeln an und bau dir deine ganz eigene Spielweise.\xa0',
        'greek': 'Γιατί να μείνεις στις έξι πλευρές; Ή δοκίμασε τις [b]παράλληλες σειρές[/b] για απόλυτο χάος. Ρύθμισε τις συνθήκες νίκης, τους κανόνες έναρξης και ενισχύσεων και φτιάξε τον δικό σου τρόπο να παίζεις. ',
        'hungarian': 'Miért állnánk meg hat oldalnál? Vagy próbáld ki a [b]párhuzamos köröket[/b] a teljes káoszért. Állítsd be a győzelmi feltételeket, a kezdési és az utánpótlási szabályokat, és rakd össze a saját játékmódodat. ',
        'indonesian': 'Kenapa harus berhenti di enam sisi? Atau coba [b]giliran sejajar[/b] untuk kekacauan maksimal. Atur syarat kemenangan, aturan awal, dan aturan bala bantuan untuk membuat cara bermainmu sendiri. ',
        'italian': 'Perché accontentarsi di sei facce? Oppure prova i [b]turni paralleli[/b] per il massimo del caos. Regola condizioni di vittoria, impostazioni iniziali e regole dei rinforzi per creare il tuo modo di giocare.\xa0',
        'japanese': '6面である必要はありません。混沌を求めるなら [b]並行ターン[/b] もどうぞ。勝利条件、開始設定、補給ルールを調整して、自分だけの遊び方を作れます。 ',
        'koreana': '여섯 면에 만족할 이유가 있을까요? 아니면 [b]동시 턴[/b]으로 최대의 혼돈을 즐겨 보세요. 승리 조건과 시작 설정, 보급 규칙을 조정해 나만의 플레이 방식을 만들 수 있습니다. ',
        'latam': '¿Por qué conformarse con seis caras? O prueba los [b]turnos paralelos[/b] para un caos total. Ajusta las condiciones de victoria, las reglas de inicio y de refuerzos para crear tu propia forma de jugar. ',
        'malay': 'Mengapa perlu berhenti pada enam sisi? Atau cuba [b]giliran selari[/b] untuk kekacauan maksimum. Laraskan syarat kemenangan, peraturan permulaan dan peraturan bantuan untuk membina cara bermain anda sendiri. ',
        'norwegian': 'Hvorfor nøye seg med seks sider? Eller prøv [b]parallelle turer[/b] for maksimalt kaos. Juster seiersvilkår, startregler og forsyningsregler, og bygg din helt egen måte å spille på. ',
        'polish': 'Po co poprzestawać na sześciu ściankach? Albo spróbuj [b]tur równoległych[/b] dla maksymalnego chaosu. Dostosuj warunki zwycięstwa, zasady startu i zaopatrzenia i zbuduj własny sposób gry. ',
        'portuguese': 'Porquê ficar pelas seis faces? Ou experimenta [b]turnos paralelos[/b] para o caos total. Ajusta condições de vitória, regras de início e de reforço e monta a tua própria forma de jogar. ',
        'romanian': 'De ce să te oprești la șase fețe? Sau încearcă [b]turele paralele[/b] pentru haos total. Reglează condițiile de victorie, regulile de start și de întăriri și construiește-ți propriul mod de a juca. ',
        'russian': 'Зачем ограничиваться шестью гранями? Или включите [b]параллельные ходы[/b] ради полного хаоса. Настройте условия победы, правила старта и подкреплений и соберите свой собственный способ играть. ',
        'schinese': '为什么只能是六个面？或者试试 [b]并行回合[/b]，体验极致混乱。调整胜利条件、开局设置和补给规则，打造属于你自己的玩法。\xa0',
        'spanish': '¿Por qué conformarse con seis caras? O prueba los [b]turnos paralelos[/b] para un caos total. Ajusta las condiciones de victoria, el modo de inicio y las reglas de refuerzos para crear tu propia forma de jugar.\xa0',
        'swedish': 'Varför nöja sig med sex sidor? Eller prova [b]parallella drag[/b] för maximalt kaos. Justera segervillkor, startregler och förstärkningsregler och bygg ditt helt egna sätt att spela. ',
        'tchinese': '為什麼只能是六個面？或者試試 [b]並行回合[/b]，體驗極致混亂。調整勝利條件、開局設定和補給規則，打造屬於你自己的玩法。 ',
        'turkish': 'Neden altı yüzle yetinelim? Ya da tam kaos için [b]paralel turları[/b] dene. Kazanma koşullarını, başlangıç ve takviye kurallarını ayarla ve kendi oynayış tarzını kur. ',
        'ukrainian': 'Навіщо обмежуватися шістьма гранями? Або ввімкни [b]паралельні ходи[/b] заради цілковитого хаосу. Налаштуй умови перемоги, правила старту й підкріплень і збери власний спосіб гри. ',
        'vietnamese': 'Tại sao phải dừng ở sáu mặt? Hoặc thử [b]lượt song song[/b] để hỗn loạn hết cỡ. Điều chỉnh điều kiện thắng, luật khởi đầu và luật tiếp viện để tạo ra lối chơi của riêng bạn. ',
    },
    {
        'english': 'Handcrafted levels with various settings are waiting for you.\xa0',
        'brazilian': 'Fases feitas à mão, cada uma com suas configurações, esperam por você. ',
        'bulgarian': 'Чакат те ръчно направени нива, всяко със свои настройки. ',
        'czech': 'Čekají na tebe ručně připravené úrovně, každá s vlastním nastavením. ',
        'danish': 'Håndlavede baner med hver deres indstillinger venter på dig. ',
        'dutch': 'Met de hand gemaakte levels, elk met eigen instellingen, staan voor je klaar. ',
        'finnish': 'Käsin tehdyt tasot, kukin omilla asetuksillaan, odottavat sinua. ',
        'french': 'Des niveaux faits main, avec des réglages variés, vous attendent.\xa0',
        'german': 'Handgebaute Level mit ganz unterschiedlichen Einstellungen warten auf dich.\xa0',
        'greek': 'Σε περιμένουν πίστες φτιαγμένες στο χέρι, η καθεμία με τις δικές της ρυθμίσεις. ',
        'hungarian': 'Kézzel készített pályák várnak rád, mindegyik a maga beállításaival. ',
        'indonesian': 'Level buatan tangan dengan aneka pengaturan sudah menantimu. ',
        'italian': 'Ti aspettano livelli creati a mano, con impostazioni sempre diverse.\xa0',
        'japanese': '設定の異なる手作りのレベルが待っています。 ',
        'koreana': '설정이 저마다 다른 수작업 레벨이 기다리고 있습니다. ',
        'latam': 'Te esperan niveles hechos a mano, cada uno con sus propios ajustes. ',
        'malay': 'Tahap buatan tangan dengan pelbagai tetapan sedang menanti anda. ',
        'norwegian': 'Håndlagde nivåer med hver sine innstillinger venter på deg. ',
        'polish': 'Czekają na ciebie ręcznie przygotowane poziomy, każdy z własnymi ustawieniami. ',
        'portuguese': 'Níveis feitos à mão, cada um com as suas definições, estão à tua espera. ',
        'romanian': 'Te așteaptă niveluri făcute manual, fiecare cu setările lui. ',
        'russian': 'Вас ждут уровни, собранные вручную, каждый со своими настройками. ',
        'schinese': '手工打造的关卡、各不相同的设置，正等着你。\xa0',
        'spanish': 'Niveles hechos a mano con ajustes muy variados te están esperando.\xa0',
        'swedish': 'Handgjorda banor med var sina inställningar väntar på dig. ',
        'tchinese': '手工打造的關卡、各不相同的設定，正等著你。 ',
        'turkish': 'El emeğiyle hazırlanmış, her biri farklı ayarlara sahip bölümler seni bekliyor. ',
        'ukrainian': 'На тебе чекають рівні, зроблені вручну, кожен зі своїми налаштуваннями. ',
        'vietnamese': 'Những màn chơi làm thủ công, mỗi màn một thiết lập riêng, đang chờ bạn. ',
    },
    {
        'english': '[h2][b]Open Source &amp; Community[/b][/h2]',
        'brazilian': '[h2][b]Código aberto e comunidade[/b][/h2]',
        'bulgarian': '[h2][b]Отворен код и общност[/b][/h2]',
        'czech': '[h2][b]Otevřený kód &amp; komunita[/b][/h2]',
        'danish': '[h2][b]Open source &amp; fællesskab[/b][/h2]',
        'dutch': '[h2][b]Opensource &amp; community[/b][/h2]',
        'finnish': '[h2][b]Avoin lähdekoodi &amp; yhteisö[/b][/h2]',
        'french': '[h2][b]Open source &amp; communauté[/b][/h2]',
        'german': '[h2][b]Offener Quellcode &amp; Community[/b][/h2]',
        'greek': '[h2][b]Ανοιχτός κώδικας &amp; κοινότητα[/b][/h2]',
        'hungarian': '[h2][b]Nyílt forráskód &amp; közösség[/b][/h2]',
        'indonesian': '[h2][b]Sumber terbuka &amp; komunitas[/b][/h2]',
        'italian': '[h2][b]Open source &amp; comunità[/b][/h2]',
        'japanese': '[h2][b]オープンソースとコミュニティ[/b][/h2]',
        'koreana': '[h2][b]오픈 소스와 커뮤니티[/b][/h2]',
        'latam': '[h2][b]Código abierto y comunidad[/b][/h2]',
        'malay': '[h2][b]Sumber terbuka &amp; komuniti[/b][/h2]',
        'norwegian': '[h2][b]Åpen kildekode &amp; fellesskap[/b][/h2]',
        'polish': '[h2][b]Otwarty kod &amp; społeczność[/b][/h2]',
        'portuguese': '[h2][b]Código aberto e comunidade[/b][/h2]',
        'romanian': '[h2][b]Sursă deschisă &amp; comunitate[/b][/h2]',
        'russian': '[h2][b]Открытый код и сообщество[/b][/h2]',
        'schinese': '[h2][b]开源与社区[/b][/h2]',
        'spanish': '[h2][b]Código abierto y comunidad[/b][/h2]',
        'swedish': '[h2][b]Öppen källkod &amp; gemenskap[/b][/h2]',
        'tchinese': '[h2][b]開放原始碼與社群[/b][/h2]',
        'turkish': '[h2][b]Açık kaynak &amp; topluluk[/b][/h2]',
        'ukrainian': '[h2][b]Відкритий код і спільнота[/b][/h2]',
        'vietnamese': '[h2][b]Mã nguồn mở và cộng đồng[/b][/h2]',
    },
    {
        'english': '[b]Diception is a passion project built on transparency.[/b] We believe that game logic should be open for everyone to study. That’s why the core engine of Diception is [b]Open Source[/b]. You can check out the code, see how the probability engine works, or even contribute.',
        'brazilian': '[b]Diception é um projeto de paixão construído sobre transparência.[/b] Acreditamos que a lógica de um jogo deve estar aberta a todos. Por isso o motor do Diception é de [b]código aberto[/b]. Você pode ler o código, ver como funciona o motor de probabilidades ou até contribuir.',
        'bulgarian': '[b]Diception е проект от любов, изграден върху прозрачност.[/b] Смятаме, че логиката на една игра трябва да е достъпна за всеки. Затова ядрото на Diception е с [b]отворен код[/b]. Можеш да разгледаш кода, да видиш как работи изчисляването на вероятностите или дори да допринесеш.',
        'czech': '[b]Diception je srdcovka postavená na otevřenosti.[/b] Myslíme si, že herní logika má být k nahlédnutí pro každého. Proto je jádro Diception [b]otevřený kód[/b]. Můžeš si kód projít, podívat se, jak funguje výpočet pravděpodobností, nebo sám přispět.',
        'danish': '[b]Diception er et hjerteprojekt bygget på åbenhed.[/b] Vi mener, at spillogik bør være til at kigge efter i sømmene for alle. Derfor er kernen i Diception [b]open source[/b]. Du kan læse koden, se hvordan sandsynlighedsmotoren fungerer, eller selv bidrage.',
        'dutch': '[b]Diception is een passieproject dat op transparantie is gebouwd.[/b] Wij vinden dat spellogica voor iedereen te bekijken hoort te zijn. Daarom is de kern van Diception [b]opensource[/b]. Je kunt de code inzien, bekijken hoe de kansberekening werkt, of zelf meehelpen.',
        'finnish': '[b]Diception on avoimuudelle rakennettu intohimoprojekti.[/b] Mielestämme pelin logiikan kuuluu olla kaikkien tutkittavissa. Siksi Diceptionin ydin on [b]avointa lähdekoodia[/b]. Voit lukea koodin, katsoa miten todennäköisyyslaskenta toimii tai osallistua itse.',
        'french': "[b]Diception est un projet passion bâti sur la transparence.[/b] Nous pensons que la logique d'un jeu devrait être ouverte à tous. C'est pourquoi le moteur de Diception est [b]open source[/b]. Vous pouvez consulter le code, voir comment fonctionne le moteur de probabilités, ou même y contribuer.",
        'german': '[b]Diception ist ein Herzensprojekt, das auf Transparenz setzt.[/b] Wir finden, dass Spiellogik für alle nachvollziehbar sein sollte. Deshalb ist die Kern-Engine von Diception [b]Open Source[/b]. Du kannst dir den Code ansehen, nachvollziehen, wie die Wahrscheinlichkeitsberechnung funktioniert, oder selbst etwas beitragen.',
        'greek': "[b]Το Diception είναι ένα έργο αγάπης χτισμένο πάνω στη διαφάνεια.[/b] Πιστεύουμε ότι η λογική ενός παιχνιδιού πρέπει να είναι ανοιχτή για να τη μελετήσει ο καθένας. Γι' αυτό ο πυρήνας του Diception είναι [b]ανοιχτός κώδικας[/b]. Μπορείς να δεις τον κώδικα, να καταλάβεις πώς δουλεύει ο υπολογισμός πιθανοτήτων, ακόμη και να συνεισφέρεις.",
        'hungarian': '[b]A Diception szenvedélyből született, az átláthatóságra építve.[/b] Úgy gondoljuk, egy játék logikájába bárki beleláthat. Ezért a Diception motorja [b]nyílt forráskódú[/b]. Átnézheted a kódot, megnézheted, hogyan működik a valószínűségszámítás, vagy akár hozzá is tehetsz.',
        'indonesian': '[b]Diception adalah proyek yang lahir dari kecintaan dan dibangun di atas keterbukaan.[/b] Kami percaya logika sebuah permainan seharusnya bisa ditelaah siapa saja. Karena itu inti mesin Diception bersifat [b]sumber terbuka[/b]. Kamu bisa membaca kodenya, melihat cara kerja mesin peluangnya, bahkan ikut berkontribusi.',
        'italian': '[b]Diception è un progetto nato dalla passione e costruito sulla trasparenza.[/b] Crediamo che la logica di un gioco debba essere aperta a tutti. Per questo il motore di Diception è [b]open source[/b]. Puoi leggere il codice, vedere come funziona il motore delle probabilità o persino contribuire.',
        'japanese': '[b]Diception は透明性の上に築かれた情熱的なプロジェクトです。[/b] ゲームのロジックは誰もが調べられるべきだと考えています。だから Diception のコアエンジンは [b]オープンソース[/b] です。コードを読み、確率エンジンの仕組みを確かめ、開発に参加することもできます。',
        'koreana': '[b]Diception은 투명성 위에 세운 애정의 결과물입니다.[/b] 게임 로직은 누구나 들여다볼 수 있어야 한다고 믿습니다. 그래서 Diception의 핵심 엔진은 [b]오픈 소스[/b]입니다. 코드를 확인하고 확률 엔진의 작동 방식을 살펴보거나 직접 기여할 수도 있습니다.',
        'latam': '[b]Diception es un proyecto hecho con pasión y basado en la transparencia.[/b] Creemos que la lógica de un juego debería estar abierta a todos. Por eso el motor de Diception es de [b]código abierto[/b]. Puedes revisar el código, ver cómo funciona el motor de probabilidades o incluso contribuir.',
        'malay': '[b]Diception ialah projek yang lahir daripada minat dan dibina atas ketelusan.[/b] Kami percaya logik sesebuah permainan sepatutnya boleh diteliti sesiapa sahaja. Sebab itu teras enjin Diception ialah [b]sumber terbuka[/b]. Anda boleh membaca kodnya, melihat cara enjin kebarangkaliannya berfungsi, malah menyumbang.',
        'norwegian': '[b]Diception er et hjerteprosjekt bygget på åpenhet.[/b] Vi mener spillogikk bør være mulig for alle å granske. Derfor er kjernen i Diception [b]åpen kildekode[/b]. Du kan lese koden, se hvordan sannsynlighetsmotoren fungerer, eller bidra selv.',
        'polish': '[b]Diception to projekt z pasji, zbudowany na przejrzystości.[/b] Uważamy, że logika gry powinna być dostępna do wglądu dla każdego. Dlatego rdzeń Diception ma [b]otwarty kod[/b]. Możesz przejrzeć kod, zobaczyć, jak działa silnik prawdopodobieństwa, albo sam coś dołożyć.',
        'portuguese': '[b]O Diception é um projeto de paixão construído sobre transparência.[/b] Acreditamos que a lógica de um jogo deve estar aberta a todos. Por isso o motor do Diception é de [b]código aberto[/b]. Podes ler o código, ver como funciona o motor de probabilidades ou até contribuir.',
        'romanian': '[b]Diception este un proiect făcut din pasiune, construit pe transparență.[/b] Credem că logica unui joc ar trebui să fie la vedere pentru oricine. De aceea nucleul jocului Diception este cu [b]sursă deschisă[/b]. Poți citi codul, vedea cum funcționează motorul de probabilități sau chiar contribui.',
        'russian': '[b]Diception сделан с любовью и построен на открытости.[/b] Мы считаем, что игровая логика должна быть доступна каждому. Поэтому движок Diception — [b]открытый код[/b]. Можно изучить его, посмотреть, как устроен расчёт вероятностей, и даже помочь с разработкой.',
        'schinese': '[b]Diception 是一个建立在透明之上的热爱之作。[/b] 我们认为游戏逻辑应该对所有人开放。因此 Diception 的核心引擎是 [b]开源[/b] 的。你可以查看代码、了解概率引擎的运作方式，甚至参与贡献。',
        'spanish': '[b]Diception es un proyecto personal basado en la transparencia.[/b] Creemos que la lógica de un juego debería estar abierta para que cualquiera la estudie. Por eso el motor de Diception es [b]código abierto[/b]. Puedes consultar el código, ver cómo funciona el cálculo de probabilidades o incluso contribuir.',
        'swedish': '[b]Diception är ett hjärteprojekt byggt på öppenhet.[/b] Vi tycker att spellogik ska gå att granska för alla. Därför är kärnan i Diception [b]öppen källkod[/b]. Du kan läsa koden, se hur sannolikhetsmotorn fungerar eller själv bidra.',
        'tchinese': '[b]Diception 是一個建立在透明之上的熱愛之作。[/b] 我們認為遊戲邏輯應該對所有人開放。因此 Diception 的核心引擎是 [b]開放原始碼[/b] 的。你可以查看程式碼、了解機率引擎的運作方式，甚至參與貢獻。',
        'turkish': "[b]Diception, şeffaflık üzerine kurulmuş bir tutku projesi.[/b] Oyun mantığının herkesin inceleyebileceği bir şey olması gerektiğine inanıyoruz. Bu yüzden Diception'ın çekirdeği [b]açık kaynak[/b]. Kodu inceleyebilir, olasılık motorunun nasıl çalıştığını görebilir, hatta katkıda bulunabilirsin.",
        'ukrainian': "[b]Diception зроблено з любов'ю та побудовано на відкритості.[/b] Ми вважаємо, що ігрова логіка має бути доступна кожному. Тому рушій Diception — [b]відкритий код[/b]. Можна переглянути його, побачити, як влаштований розрахунок імовірностей, і навіть допомогти з розробкою.",
        'vietnamese': '[b]Diception là một dự án tâm huyết, xây trên sự minh bạch.[/b] Chúng tôi tin rằng logic của một trò chơi nên để ai cũng xem được. Vì vậy phần lõi của Diception là [b]mã nguồn mở[/b]. Bạn có thể đọc mã, xem cách bộ tính xác suất hoạt động, thậm chí đóng góp.',
    },
    {
        'english': '[h2][b]Full Version vs. Demo[/b][/h2]',
        'brazilian': '[h2][b]Versão completa e demo[/b][/h2]',
        'bulgarian': '[h2][b]Пълна версия и демо[/b][/h2]',
        'czech': '[h2][b]Plná verze a demo[/b][/h2]',
        'danish': '[h2][b]Fuld version og demo[/b][/h2]',
        'dutch': '[h2][b]Volledige versie en demo[/b][/h2]',
        'finnish': '[h2][b]Täysi versio ja kokeiluversio[/b][/h2]',
        'french': '[h2][b]Version complète et démo[/b][/h2]',
        'german': '[h2][b]Vollversion und Demo[/b][/h2]',
        'greek': '[h2][b]Πλήρης έκδοση και δοκιμαστική[/b][/h2]',
        'hungarian': '[h2][b]Teljes változat és demó[/b][/h2]',
        'indonesian': '[h2][b]Versi lengkap dan demo[/b][/h2]',
        'italian': '[h2][b]Versione completa e demo[/b][/h2]',
        'japanese': '[h2][b]製品版とデモ[/b][/h2]',
        'koreana': '[h2][b]정식 버전과 체험판[/b][/h2]',
        'latam': '[h2][b]Versión completa y demo[/b][/h2]',
        'malay': '[h2][b]Versi penuh dan demo[/b][/h2]',
        'norwegian': '[h2][b]Full versjon og demo[/b][/h2]',
        'polish': '[h2][b]Pełna wersja i demo[/b][/h2]',
        'portuguese': '[h2][b]Versão completa e demo[/b][/h2]',
        'romanian': '[h2][b]Versiunea completă și demoul[/b][/h2]',
        'russian': '[h2][b]Полная версия и демо[/b][/h2]',
        'schinese': '[h2][b]完整版与试玩版[/b][/h2]',
        'spanish': '[h2][b]Versión completa y demo[/b][/h2]',
        'swedish': '[h2][b]Fullversion och demo[/b][/h2]',
        'tchinese': '[h2][b]完整版與試玩版[/b][/h2]',
        'turkish': '[h2][b]Tam sürüm ve demo[/b][/h2]',
        'ukrainian': '[h2][b]Повна версія та демо[/b][/h2]',
        'vietnamese': '[h2][b]Bản đầy đủ và bản dùng thử[/b][/h2]',
    },
    {
        'english': 'The [b]free demo[/b] offers a balanced 1vs2 bot setup on a medium-sized map. This specific configuration is one of the most fun ways to play and will remain free forever!',
        'brazilian': 'A [b]demo gratuita[/b] traz uma partida equilibrada de 1 contra 2 bots em um mapa médio. Essa configuração é uma das mais divertidas e vai continuar gratuita para sempre!',
        'bulgarian': '[b]Безплатното демо[/b] предлага балансирана партия 1 срещу 2 бота на карта със среден размер. Точно тази конфигурация е един от най-забавните начини за игра и ще остане безплатна завинаги!',
        'czech': '[b]Demo zdarma[/b] nabízí vyrovnanou partii 1 proti 2 botům na středně velké mapě. Právě tahle sestava patří k nejzábavnějším způsobům hraní a zůstane zdarma navždy!',
        'danish': '[b]Den gratis demo[/b] byder på et afbalanceret parti med 1 mod 2 botter på et mellemstort kort. Netop den opsætning er en af de sjoveste måder at spille på, og den bliver gratis for altid!',
        'dutch': 'De [b]gratis demo[/b] biedt een uitgebalanceerde partij van 1 tegen 2 bots op een middelgrote kaart. Deze opzet is een van de leukste manieren om te spelen en blijft voor altijd gratis!',
        'finnish': '[b]Ilmainen kokeiluversio[/b] tarjoaa tasapainoisen ottelun 1 vastaan 2 bottia keskikokoisella kartalla. Juuri tuo kokoonpano on yksi hauskimmista tavoista pelata, ja se pysyy ilmaisena ikuisesti!',
        'french': "La [b]démo gratuite[/b] propose une partie équilibrée à 1 contre 2 bots sur une carte de taille moyenne. Cette configuration est l'une des plus amusantes, et elle restera gratuite pour toujours !",
        'german': 'Die [b]kostenlose Demo[/b] bietet eine ausgewogene Partie 1 gegen 2 Bots auf einer mittelgroßen Karte. Genau diese Konstellation macht besonders viel Spaß und bleibt für immer kostenlos!',
        'greek': 'Η [b]δωρεάν δοκιμαστική έκδοση[/b] προσφέρει μια ισορροπημένη παρτίδα 1 εναντίον 2 μποτ σε χάρτη μεσαίου μεγέθους. Αυτή ακριβώς η διάταξη είναι από τους πιο διασκεδαστικούς τρόπους παιχνιδιού και θα μείνει δωρεάν για πάντα!',
        'hungarian': 'Az [b]ingyenes demó[/b] kiegyensúlyozott, 1 a 2 bot elleni meccset kínál közepes méretű pályán. Éppen ez az összeállítás az egyik legszórakoztatóbb játékmód, és örökre ingyenes marad!',
        'indonesian': '[b]Demo gratis[/b] menyuguhkan pertandingan berimbang 1 lawan 2 bot di peta berukuran sedang. Justru susunan inilah salah satu cara bermain paling seru, dan akan tetap gratis selamanya!',
        'italian': 'La [b]demo gratuita[/b] offre una partita equilibrata da 1 contro 2 bot su una mappa di medie dimensioni. È una delle configurazioni più divertenti e resterà gratuita per sempre!',
        'japanese': '[b]無料デモ[/b] では、中サイズのマップで 1 対 2 ボットのバランスの取れた対戦が遊べます。この構成は最も楽しい遊び方のひとつで、これからもずっと無料です！',
        'koreana': '[b]무료 체험판[/b]에서는 중간 크기 맵에서 1대2 봇의 균형 잡힌 대전을 즐길 수 있습니다. 이 구성은 가장 재미있는 플레이 방식 중 하나이며 앞으로도 계속 무료입니다!',
        'latam': 'La [b]demo gratuita[/b] ofrece una partida equilibrada de 1 contra 2 bots en un mapa mediano. Esta configuración es una de las más divertidas y seguirá siendo gratis para siempre.',
        'malay': '[b]Demo percuma[/b] menawarkan perlawanan seimbang 1 lawan 2 bot pada peta bersaiz sederhana. Susunan inilah salah satu cara bermain paling seronok, dan ia akan kekal percuma selamanya!',
        'norwegian': '[b]Den gratis demoen[/b] byr på et balansert parti med 1 mot 2 botter på et mellomstort kart. Nettopp det oppsettet er en av de morsomste måtene å spille på, og det forblir gratis for alltid!',
        'polish': '[b]Darmowe demo[/b] oferuje wyrównaną partię 1 na 2 boty na mapie średniej wielkości. Ten układ to jeden z najprzyjemniejszych sposobów gry i pozostanie darmowy na zawsze!',
        'portuguese': 'A [b]demo gratuita[/b] traz uma partida equilibrada de 1 contra 2 bots num mapa médio. Esta configuração é uma das mais divertidas e vai continuar gratuita para sempre!',
        'romanian': '[b]Demoul gratuit[/b] oferă o partidă echilibrată de 1 contra 2 boți pe o hartă medie. Tocmai această configurație este una dintre cele mai distractive și va rămâne gratuită pentru totdeauna!',
        'russian': '[b]Бесплатное демо[/b] предлагает сбалансированную партию 1 против 2 ботов на карте среднего размера. Это одна из самых интересных конфигураций, и она навсегда останется бесплатной!',
        'schinese': '[b]免费试玩版[/b] 提供中等地图上 1 对 2 电脑的均衡配置。这一特定配置是本作最有趣的玩法之一，并将永久免费！',
        'spanish': 'La [b]demo gratuita[/b] ofrece una partida equilibrada de 1 contra 2 bots en un mapa mediano. Esa configuración concreta es una de las más divertidas del juego, y seguirá siendo gratis para siempre.',
        'swedish': '[b]Den gratis demon[/b] bjuder på ett balanserat parti med 1 mot 2 bottar på en medelstor karta. Just den uppsättningen är ett av de roligaste sätten att spela, och den förblir gratis för alltid!',
        'tchinese': '[b]免費試玩版[/b] 提供中等地圖上 1 對 2 電腦的均衡配置。這一特定配置是本作最有趣的玩法之一，並將永久免費！',
        'turkish': "[b]Ücretsiz demo[/b], orta boy bir haritada 1'e 2 bota karşı dengeli bir maç sunuyor. Tam da bu kurulum, oyunun en keyifli hallerinden biri ve sonsuza dek ücretsiz kalacak!",
        'ukrainian': '[b]Безкоштовне демо[/b] пропонує збалансовану партію 1 проти 2 ботів на карті середнього розміру. Саме ця конфігурація — один із найцікавіших способів грати, і вона назавжди залишиться безкоштовною!',
        'vietnamese': '[b]Bản dùng thử miễn phí[/b] mang đến ván đấu cân bằng 1 chọi 2 bot trên bản đồ cỡ vừa. Chính cấu hình này là một trong những cách chơi thú vị nhất, và sẽ miễn phí mãi mãi!',
    },
    {
        'english': '[b]By purchasing the full version, you unlock:[/b]',
        'brazilian': '[b]Ao comprar a versão completa, você desbloqueia:[/b]',
        'bulgarian': '[b]С покупката на пълната версия отключваш:[/b]',
        'czech': '[b]Koupí plné verze si odemkneš:[/b]',
        'danish': '[b]Med den fulde version låser du op for:[/b]',
        'dutch': '[b]Met de volledige versie ontgrendel je:[/b]',
        'finnish': '[b]Ostamalla täyden version avaat:[/b]',
        'french': '[b]En achetant la version complète, vous débloquez :[/b]',
        'german': '[b]Mit dem Kauf der Vollversion schaltest du frei:[/b]',
        'greek': '[b]Αγοράζοντας την πλήρη έκδοση ξεκλειδώνεις:[/b]',
        'hungarian': '[b]A teljes változat megvásárlásával feloldod:[/b]',
        'indonesian': '[b]Dengan membeli versi lengkap, kamu membuka:[/b]',
        'italian': '[b]Acquistando la versione completa sblocchi:[/b]',
        'japanese': '[b]製品版を購入すると解放されるもの：[/b]',
        'koreana': '[b]정식 버전을 구매하면 열리는 것:[/b]',
        'latam': '[b]Al comprar la versión completa desbloqueas:[/b]',
        'malay': '[b]Dengan membeli versi penuh, anda membuka:[/b]',
        'norwegian': '[b]Med full versjon låser du opp:[/b]',
        'polish': '[b]Kupując pełną wersję, odblokowujesz:[/b]',
        'portuguese': '[b]Ao comprares a versão completa, desbloqueias:[/b]',
        'romanian': '[b]Cumpărând versiunea completă deblochezi:[/b]',
        'russian': '[b]Покупая полную версию, вы открываете:[/b]',
        'schinese': '[b]购买完整版即可解锁：[/b]',
        'spanish': '[b]Al comprar la versión completa desbloqueas:[/b]',
        'swedish': '[b]Med fullversionen låser du upp:[/b]',
        'tchinese': '[b]購買完整版即可解鎖：[/b]',
        'turkish': '[b]Tam sürümü satın alarak şunların kilidini açarsın:[/b]',
        'ukrainian': '[b]Купуючи повну версію, ти відкриваєш:[/b]',
        'vietnamese': '[b]Khi mua bản đầy đủ, bạn mở khóa:[/b]',
    },
    {
        'english': 'The complete [b]campaign[/b].',
        'brazilian': 'A [b]campanha[/b] completa.',
        'bulgarian': 'Цялата [b]кампания[/b].',
        'czech': 'Celou [b]kampaň[/b].',
        'danish': 'Hele [b]kampagnen[/b].',
        'dutch': 'De volledige [b]campagne[/b].',
        'finnish': 'Koko [b]kampanjan[/b].',
        'french': 'La [b]campagne[/b] complète.',
        'german': 'Die komplette [b]Kampagne[/b].',
        'greek': 'Ολόκληρη την [b]εκστρατεία[/b].',
        'hungarian': 'A teljes [b]kampányt[/b].',
        'indonesian': '[b]Kampanye[/b] selengkapnya.',
        'italian': 'La [b]campagna[/b] completa.',
        'japanese': '完全版の [b]キャンペーン[/b]。',
        'koreana': '전체 [b]캠페인[/b].',
        'latam': 'La [b]campaña[/b] completa.',
        'malay': '[b]Kempen[/b] sepenuhnya.',
        'norwegian': 'Hele [b]kampanjen[/b].',
        'polish': 'Pełną [b]kampanię[/b].',
        'portuguese': 'A [b]campanha[/b] completa.',
        'romanian': '[b]Campania[/b] completă.',
        'russian': 'Полную [b]кампанию[/b].',
        'schinese': '完整的[b]战役[/b]。',
        'spanish': 'La [b]campaña[/b] completa.',
        'swedish': 'Hela [b]kampanjen[/b].',
        'tchinese': '完整的[b]戰役[/b]。',
        'turkish': 'Kampanyanın [b]tamamı[/b].',
        'ukrainian': 'Повну [b]кампанію[/b].',
        'vietnamese': 'Toàn bộ [b]chiến dịch[/b].',
    },
    {
        'english': '[b]Bigger Maps[/b] and Bots with higher difficulty.',
        'brazilian': '[b]Mapas maiores[/b] e bots mais difíceis.',
        'bulgarian': '[b]По-големи карти[/b] и ботове с по-висока трудност.',
        'czech': '[b]Větší mapy[/b] a boty s vyšší obtížností.',
        'danish': '[b]Større kort[/b] og botter med højere sværhedsgrad.',
        'dutch': '[b]Grotere kaarten[/b] en bots met een hogere moeilijkheidsgraad.',
        'finnish': '[b]Isommat kartat[/b] ja vaikeammat botit.',
        'french': 'Des [b]cartes plus grandes[/b] et des bots plus coriaces.',
        'german': '[b]Größere Karten[/b] und Bots mit höherem Schwierigkeitsgrad.',
        'greek': '[b]Μεγαλύτερους χάρτες[/b] και μποτ μεγαλύτερης δυσκολίας.',
        'hungarian': '[b]Nagyobb pályákat[/b] és nehezebb botokat.',
        'indonesian': '[b]Peta yang lebih luas[/b] dan bot dengan tingkat kesulitan lebih tinggi.',
        'italian': '[b]Mappe più grandi[/b] e bot di difficoltà superiore.',
        'japanese': '[b]より大きなマップ[/b] と、より手強いボット。',
        'koreana': '[b]더 큰 맵[/b]과 난이도가 높은 봇.',
        'latam': '[b]Mapas más grandes[/b] y bots más difíciles.',
        'malay': '[b]Peta yang lebih luas[/b] dan bot dengan tahap kesukaran lebih tinggi.',
        'norwegian': '[b]Større kart[/b] og botter med høyere vanskelighetsgrad.',
        'polish': '[b]Większe mapy[/b] i boty o wyższym poziomie trudności.',
        'portuguese': '[b]Mapas maiores[/b] e bots mais difíceis.',
        'romanian': '[b]Hărți mai mari[/b] și boți cu dificultate ridicată.',
        'russian': '[b]Карты побольше[/b] и ботов посложнее.',
        'schinese': '[b]更大的地图[/b]和难度更高的电脑对手。',
        'spanish': '[b]Mapas más grandes[/b] y bots de mayor dificultad.',
        'swedish': '[b]Större kartor[/b] och bottar med högre svårighetsgrad.',
        'tchinese': '[b]更大的地圖[/b]和難度更高的電腦對手。',
        'turkish': '[b]Daha büyük haritalar[/b] ve daha zorlu botlar.',
        'ukrainian': '[b]Більші карти[/b] й складніших ботів.',
        'vietnamese': '[b]Bản đồ rộng hơn[/b] và bot có độ khó cao hơn.',
    },
    {
        'english': '[b]Local Multiplayer[/b] for up to 8 players (supports Gamepads and Mobile Phones as input).',
        'brazilian': '[b]Multijogador local[/b] para até 8 jogadores (controles e celulares funcionam como controle).',
        'bulgarian': '[b]Локална игра[/b] за до 8 играчи (контролерите и телефоните може да се използват за управление).',
        'czech': '[b]Místní hru[/b] až pro 8 hráčů (gamepady i telefony fungují jako ovladač).',
        'danish': '[b]Lokal flerspiller[/b] for op til 8 spillere (controllere og mobiltelefoner kan bruges som styring).',
        'dutch': '[b]Lokale multiplayer[/b] voor maximaal 8 spelers (controllers en telefoons werken als besturing).',
        'finnish': '[b]Paikallisen moninpelin[/b] jopa 8 pelaajalle (ohjaimet ja puhelimet käyvät ohjaimiksi).',
        'french': "Le [b]multijoueur local[/b] jusqu'à 8 joueurs (manettes et téléphones acceptés comme manettes).",
        'german': '[b]Lokalen Mehrspieler[/b] für bis zu 8 Spieler (Gamepads und Smartphones als Eingabegeräte werden unterstützt).',
        'greek': '[b]Τοπικό παιχνίδι[/b] για έως 8 παίκτες (χειριστήρια και κινητά μπορούν να χρησιμοποιηθούν ως χειριστήριο).',
        'hungarian': 'A [b]helyi többjátékos módot[/b] akár 8 játékosnak (a kontrollerek és a telefonok is használhatók vezérlőként).',
        'indonesian': '[b]Main bersama di satu perangkat[/b] hingga 8 pemain (gamepad dan ponsel bisa dipakai sebagai kendali).',
        'italian': 'Il [b]multigiocatore locale[/b] fino a 8 giocatori (controller e telefoni utilizzabili come comandi).',
        'japanese': '最大8人の [b]ローカル対戦[/b]（ゲームパッドやスマートフォンをコントローラーとして使えます）。',
        'koreana': '최대 8인 [b]로컬 멀티플레이[/b](게임패드와 휴대폰을 조작 장치로 사용 가능).',
        'latam': '[b]Multijugador local[/b] para hasta 8 jugadores (los controles y los celulares sirven como mando).',
        'malay': '[b]Permainan bersama pada satu peranti[/b] untuk sehingga 8 pemain (gamepad dan telefon boleh digunakan sebagai kawalan).',
        'norwegian': '[b]Lokal flerspiller[/b] for opptil 8 spillere (håndkontroller og mobiltelefoner kan brukes som styring).',
        'polish': '[b]Grę lokalną[/b] nawet dla 8 osób (pady i telefony działają jako sterowanie).',
        'portuguese': '[b]Multijogador local[/b] até 8 jogadores (comandos e telemóveis funcionam como comando).',
        'romanian': '[b]Jocul local[/b] pentru până la 8 jucători (controlerele și telefoanele pot fi folosite pe post de comandă).',
        'russian': '[b]Локальную игру[/b] до 8 человек (геймпады и телефоны можно использовать как контроллеры).',
        'schinese': '最多 8 人的[b]本地多人游戏[/b]（支持手柄和手机作为输入设备）。',
        'spanish': '[b]Multijugador local[/b] para hasta 8 jugadores (admite mandos y teléfonos móviles como mando).',
        'swedish': '[b]Lokalt flerspelarläge[/b] för upp till 8 spelare (handkontroller och mobiltelefoner kan användas som styrning).',
        'tchinese': '最多 8 人的[b]本機多人遊戲[/b]（支援手把和手機作為輸入裝置）。',
        'turkish': '8 oyuncuya kadar [b]yerel çok oyunculu mod[/b] (oyun kumandaları ve telefonlar kumanda olarak kullanılabilir).',
        'ukrainian': '[b]Локальну гру[/b] до 8 осіб (геймпади й телефони можна використовувати як контролери).',
        'vietnamese': '[b]Chơi chung trên một máy[/b] cho tối đa 8 người (tay cầm và điện thoại đều dùng được để điều khiển).',
    },
    {
        'english': '[b] Mods:[/b] Parallel turns, special attack/win rules, custom dice sides, and turn limits.',
        'brazilian': '[b] Mods:[/b] turnos paralelos, regras especiais de ataque e vitória, faces de dado personalizadas e limites de turno.',
        'bulgarian': '[b] Mods:[/b] паралелни ходове, специални правила за атака и победа, свободен избор на страни на зара и ограничения на ходовете.',
        'czech': '[b] Mods:[/b] paralelní tahy, zvláštní pravidla útoku a vítězství, libovolný počet stěn kostky a limity tahů.',
        'danish': '[b] Mods:[/b] parallelle ture, særlige angrebs- og sejrsregler, frit valg af terningsider og turgrænser.',
        'dutch': '[b] Mods:[/b] parallelle beurten, speciale aanvals- en winregels, zelf gekozen dobbelsteenzijden en beurtlimieten.',
        'finnish': '[b] Mods:[/b] rinnakkaiset vuorot, erityiset hyökkäys- ja voittosäännöt, vapaasti valittavat nopan sivut ja vuororajat.',
        'french': "[b] Mods :[/b] tours parallèles, règles spéciales d'attaque et de victoire, nombre de faces au choix et limites de tour.",
        'german': '[b] Mods:[/b] Parallele Züge, besondere Angriffs- und Siegregeln, frei wählbare Würfelseiten und Zuglimits.',
        'greek': '[b] Mods:[/b] παράλληλες σειρές, ειδικοί κανόνες επίθεσης και νίκης, ελεύθερη επιλογή πλευρών ζαριού και όρια σειρών.',
        'hungarian': '[b] Mods:[/b] párhuzamos körök, különleges támadási és győzelmi szabályok, szabadon választható kockaoldalak és körkorlátok.',
        'indonesian': '[b] Mods:[/b] giliran sejajar, aturan serangan dan kemenangan khusus, jumlah sisi dadu sesuka hati, dan batas giliran.',
        'italian': '[b] Mods:[/b] turni paralleli, regole speciali di attacco e vittoria, facce dei dadi personalizzabili e limiti di turno.',
        'japanese': '[b] Mods：[/b]並行ターン、特殊な攻撃・勝利ルール、自由なサイコロの面数、ターン制限。',
        'koreana': '[b] Mods:[/b] 동시 턴, 특수 공격·승리 규칙, 원하는 주사위 면 수, 턴 제한.',
        'latam': '[b] Mods:[/b] turnos paralelos, reglas especiales de ataque y victoria, caras de dado personalizables y límites de turno.',
        'malay': '[b] Mods:[/b] giliran selari, peraturan serangan dan kemenangan khas, bilangan sisi dadu sesuka hati, dan had giliran.',
        'norwegian': '[b] Mods:[/b] parallelle turer, spesielle angreps- og seiersregler, fritt valg av terningsider og turgrenser.',
        'polish': '[b] Mods:[/b] tury równoległe, specjalne zasady ataku i zwycięstwa, dowolna liczba ścianek kostki i limity tur.',
        'portuguese': '[b] Mods:[/b] turnos paralelos, regras especiais de ataque e vitória, faces de dado personalizadas e limites de turno.',
        'romanian': '[b] Mods:[/b] ture paralele, reguli speciale de atac și de victorie, fețe de zar la alegere și limite de tură.',
        'russian': '[b] Моды:[/b] параллельные ходы, особые правила атаки и победы, произвольное число граней и лимиты ходов.',
        'schinese': '[b] 模组：[/b]并行回合、特殊的进攻／胜利规则、自定义骰子面数和回合上限。',
        'spanish': '[b] Mods:[/b] Turnos paralelos, reglas especiales de ataque y victoria, caras de dado personalizables y límites de turno.',
        'swedish': '[b] Mods:[/b] parallella drag, särskilda attack- och segerregler, fritt val av tärningssidor och draggränser.',
        'tchinese': '[b] 模組：[/b]並行回合、特殊的進攻／勝利規則、自訂骰子面數和回合上限。',
        'turkish': '[b] Mods:[/b] paralel turlar, özel saldırı ve kazanma kuralları, istediğin kadar zar yüzü ve tur sınırları.',
        'ukrainian': '[b] Моди:[/b] паралельні ходи, особливі правила атаки й перемоги, довільна кількість граней і ліміти ходів.',
        'vietnamese': '[b] Mods:[/b] lượt song song, luật tấn công và luật thắng đặc biệt, số mặt xúc xắc tùy ý, và giới hạn lượt.',
    },
    {
        'english': '[b]Steam-exclusive features:[/b] Cloud Saves, Achievements, and Remote Play Together.',
        'brazilian': '[b]Recursos exclusivos da Steam:[/b] saves na nuvem, conquistas e Remote Play Together.',
        'bulgarian': '[b]Само в Steam:[/b] запазване в облака, постижения и Remote Play Together.',
        'czech': '[b]Funkce jen na Steamu:[/b] ukládání do cloudu, achievementy a Remote Play Together.',
        'danish': '[b]Steam-eksklusive funktioner:[/b] skylagring, præstationer og Remote Play Together.',
        'dutch': '[b]Steam-exclusieve functies:[/b] cloudopslag, prestaties en Remote Play Together.',
        'finnish': '[b]Vain Steamissä:[/b] pilvitallennukset, saavutukset ja Remote Play Together.',
        'french': '[b]Fonctionnalités exclusives à Steam :[/b] sauvegardes dans le cloud, succès et Remote Play Together.',
        'german': '[b]Steam-exklusive Funktionen:[/b] Cloud-Speicherstände, Erfolge und Remote Play Together.',
        'greek': '[b]Αποκλειστικά στο Steam:[/b] αποθηκεύσεις στο cloud, επιτεύγματα και Remote Play Together.',
        'hungarian': '[b]Csak Steamen elérhető:[/b] felhőmentés, teljesítmények és Remote Play Together.',
        'indonesian': '[b]Hanya di Steam:[/b] simpanan awan, pencapaian, dan Remote Play Together.',
        'italian': '[b]Funzioni esclusive di Steam:[/b] salvataggi nel cloud, obiettivi e Remote Play Together.',
        'japanese': '[b]Steam限定の機能：[/b]クラウドセーブ、実績、Remote Play Together。',
        'koreana': '[b]Steam 전용 기능:[/b] 클라우드 저장, 도전 과제, Remote Play Together.',
        'latam': '[b]Funciones exclusivas de Steam:[/b] guardado en la nube, logros y Remote Play Together.',
        'malay': '[b]Hanya di Steam:[/b] simpanan awan, pencapaian, dan Remote Play Together.',
        'norwegian': '[b]Steam-eksklusive funksjoner:[/b] skylagring, prestasjoner og Remote Play Together.',
        'polish': '[b]Funkcje wyłącznie na Steamie:[/b] zapisy w chmurze, osiągnięcia i Remote Play Together.',
        'portuguese': '[b]Funcionalidades exclusivas da Steam:[/b] gravações na nuvem, proezas e Remote Play Together.',
        'romanian': '[b]Funcții exclusive Steam:[/b] salvări în cloud, realizări și Remote Play Together.',
        'russian': '[b]Возможности только в Steam:[/b] облачные сохранения, достижения и Remote Play Together.',
        'schinese': '[b]Steam 独占功能：[/b]云存档、成就和 Remote Play Together。',
        'spanish': '[b]Funciones exclusivas de Steam:[/b] guardado en la nube, logros y Remote Play Together.',
        'swedish': '[b]Steam-exklusiva funktioner:[/b] molnsparningar, prestationer och Remote Play Together.',
        'tchinese': '[b]Steam 獨佔功能：[/b]雲端存檔、成就和 Remote Play Together。',
        'turkish': "[b]Yalnızca Steam'de:[/b] bulut kayıtları, başarımlar ve Remote Play Together.",
        'ukrainian': '[b]Можливості лише в Steam:[/b] хмарні збереження, досягнення та Remote Play Together.',
        'vietnamese': '[b]Chỉ có trên Steam:[/b] lưu trên đám mây, thành tích và Remote Play Together.',
    },
]

SHORT_TEXT = {
    'brazilian': 'Esqueça mapas isométricos e animações lentas. Diception é um jogo de conquista por turnos ultrarrápido em uma grade 2D limpa. Fácil de aprender, difícil de dominar. Mouse, teclado e controle, mods, multijogador local para 8 e Remote Play. Go!',
    'bulgarian': 'Забрави изометричните карти и бавните анимации. Diception е светкавично бърза игра за завладяване на ходове върху чиста 2D мрежа. Лесна за научаване, трудна за овладяване. Мишка, клавиатура и контролер, Mods, локална игра за 8 и Remote Play. Go!',
    'czech': 'Zapomeň na izometrické mapy a pomalé animace. Diception je bleskurychlá tahová dobyvatelská hra na čisté 2D mřížce. Snadné naučit, těžké zvládnout. Myš, klávesnice a gamepad, mods, místní hra pro 8 a Remote Play. Go!',
    'danish': 'Glem isometriske kort og langsomme animationer. Diception er et lynhurtigt turbaseret erobringsspil på et rent 2D-gitter. Let at lære, svært at mestre. Mus, tastatur og controller, mods, lokal flerspiller for 8 og Remote Play. Go!',
    'dutch': 'Vergeet isometrische kaarten en trage animaties. Diception is een razendsnel beurtgebaseerd veroveringsspel op een strak 2D-raster. Makkelijk te leren, moeilijk te beheersen. Muis, toetsenbord en controller, mods, lokale multiplayer voor 8 en Remote Play. Go!',
    'finnish': 'Unohda isometriset kartat ja hitaat animaatiot. Diception on salamannopea vuoropohjainen valloituspeli selkeällä 2D-ruudukolla. Helppo oppia, vaikea hallita. Hiiri, näppäimistö ja ohjain, Mods, paikallinen moninpeli kahdeksalle ja Remote Play. Go!',
    'french': 'Oubliez les cartes isométriques et les animations lentes. Diception est un jeu de conquête au tour par tour ultra-rapide sur une grille 2D épurée. Facile à apprendre, difficile à maîtriser. Souris, clavier et manette, mods, multijoueur local à 8 et Remote Play. Go !',
    'german': 'Schluss mit isometrischen Karten und langsamen Animationen. Diception ist ein blitzschnelles rundenbasiertes Eroberungsspiel auf einem klaren 2D-Raster. Leicht zu lernen, schwer zu meistern. Maus, Tastatur und Gamepad, Mods, lokaler Mehrspieler für 8 und Remote Play. Go!',
    'greek': 'Ξέχνα τους ισομετρικούς χάρτες και τα αργά εφέ. Το Diception είναι ένα αστραπιαίο παιχνίδι κατάκτησης με σειρές, πάνω σε ένα καθαρό πλέγμα 2D. Εύκολο να το μάθεις, δύσκολο να το κατακτήσεις. Ποντίκι, πληκτρολόγιο και χειριστήριο, Mods, τοπικό παιχνίδι για 8 και Remote Play. Go!',
    'hungarian': 'Felejtsd el az izometrikus pályákat és a lassú animációkat. A Diception villámgyors, körökre osztott hódítós játék letisztult 2D rácson. Könnyű megtanulni, nehéz mesterévé válni. Egér, billentyűzet és kontroller, mods, 8 fős helyi többjátékos mód és Remote Play. Go!',
    'indonesian': 'Lupakan peta isometrik dan animasi yang lambat. Diception adalah permainan penaklukan bergiliran yang sangat cepat di atas grid 2D yang bersih. Mudah dipelajari, sulit dikuasai. Mouse, keyboard, dan gamepad, Mods, main bersama 8 pemain, dan Remote Play. Go!',
    'italian': 'Dimentica le mappe isometriche e le animazioni lente. Diception è un gioco di conquista a turni fulmineo su una griglia 2D pulita. Facile da imparare, difficile da padroneggiare. Mouse, tastiera e controller, mods, multigiocatore locale a 8 e Remote Play. Go!',
    'japanese': 'アイソメトリックなマップと遅いアニメーションはもう不要。Diception は、すっきりした2Dグリッドで遊ぶ超高速のターン制陣取りゲームです。覚えるのは簡単、極めるのは大変。マウス・キーボード・ゲームパッド対応、Mods、8人ローカル対戦、Remote Play。Go!',
    'koreana': '아이소메트릭 맵과 느린 애니메이션은 이제 그만. Diception은 깔끔한 2D 격자 위에서 즐기는 초고속 턴제 정복 게임입니다. 배우기는 쉽고 통달하기는 어렵습니다. 마우스·키보드·게임패드 지원, Mods, 8인 로컬 멀티플레이, Remote Play. Go!',
    'latam': 'Olvídate de los mapas isométricos y las animaciones lentas. Diception es un juego de conquista por turnos ultrarrápido sobre una cuadrícula 2D limpia. Fácil de aprender, difícil de dominar. Mouse, teclado y control, mods, multijugador local para 8 y Remote Play. ¡Vamos!',
    'malay': 'Lupakan peta isometrik dan animasi yang perlahan. Diception ialah permainan penaklukan bergilir yang amat pantas di atas grid 2D yang kemas. Mudah dipelajari, sukar dikuasai. Tetikus, papan kekunci dan gamepad, Mods, permainan bersama untuk 8 pemain, dan Remote Play. Go!',
    'norwegian': 'Glem isometriske kart og trege animasjoner. Diception er et lynraskt turbasert erobringsspill på et rent 2D-rutenett. Lett å lære, vanskelig å mestre. Mus, tastatur og håndkontroll, mods, lokal flerspiller for 8 og Remote Play. Go!',
    'polish': 'Zapomnij o mapach izometrycznych i powolnych animacjach. Diception to błyskawiczna turowa gra o podboju na czystej siatce 2D. Łatwa do nauczenia, trudna do opanowania. Mysz, klawiatura i pad, mods, gra lokalna dla 8 osób i Remote Play. Go!',
    'portuguese': 'Esquece os mapas isométricos e as animações lentas. O Diception é um jogo de conquista por turnos ultrarrápido numa grelha 2D limpa. Fácil de aprender, difícil de dominar. Rato, teclado e comando, mods, multijogador local até 8 e Remote Play. Go!',
    'romanian': 'Uită de hărțile izometrice și de animațiile lente. Diception este un joc de cucerire pe ture, fulgerător, pe o grilă 2D curată. Ușor de învățat, greu de stăpânit. Mouse, tastatură și controler, mods, joc local pentru 8 și Remote Play. Go!',
    'russian': 'Забудьте про изометрические карты и медленные анимации. Diception — молниеносная пошаговая игра о завоевании на чистой 2D-сетке. Легко освоить, трудно освоить до конца. Мышь, клавиатура и геймпад, моды, локальная игра на 8 и Remote Play. Go!',
    'schinese': '别再忍受等距地图和缓慢动画。Diception 是一款在清爽 2D 网格上进行的极速回合制征服游戏。易于上手，难于精通。支持鼠标、键盘和手柄，含模组、8 人本地多人和 Remote Play。Go!',
    'spanish': 'Olvídate de los mapas isométricos y las animaciones lentas. Diception es un juego de conquista por turnos ultrarrápido sobre una rejilla 2D limpia. Fácil de aprender, difícil de dominar. Ratón, teclado y mando, mods, multijugador local para 8 y Remote Play. ¡Vamos!',
    'swedish': 'Glöm isometriska kartor och långsamma animationer. Diception är ett blixtsnabbt turordningsbaserat erövringsspel på ett rent 2D-rutnät. Lätt att lära, svårt att bemästra. Mus, tangentbord och handkontroll, mods, lokalt flerspelarläge för 8 och Remote Play. Go!',
    'tchinese': '別再忍受等距地圖和緩慢動畫。Diception 是一款在清爽 2D 網格上進行的極速回合制征服遊戲。易於上手，難於精通。支援滑鼠、鍵盤和手把，含模組、8 人本機多人和 Remote Play。Go!',
    'turkish': 'İzometrik haritaları ve yavaş animasyonları unut. Diception, sade bir 2B ızgarada oynanan yıldırım hızında sıra tabanlı bir fetih oyunu. Öğrenmesi kolay, ustalaşması zor. Fare, klavye ve kumanda desteği, Mods, 8 kişilik yerel çok oyunculu mod ve Remote Play. Go!',
    'ukrainian': 'Забудь про ізометричні карти й повільні анімації. Diception — блискавична покрокова гра про завоювання на чистій 2D-сітці. Легко освоїти, важко опанувати. Миша, клавіатура й геймпад, моди, локальна гра на 8 і Remote Play. Go!',
    'vietnamese': 'Quên đi bản đồ đẳng cự và hiệu ứng chậm chạp. Diception là trò chơi chinh phục theo lượt cực nhanh trên một lưới 2D gọn gàng. Dễ học, khó thành thạo. Hỗ trợ chuột, bàn phím và tay cầm, Mods, chơi chung 8 người trên một máy và Remote Play. Go!',
}

SYSREQS = {
    'app[content][sysreqs][mac][min][osversion]': {
        'brazilian': 'macOS 10.13 (High Sierra)',
        'bulgarian': 'macOS 10.13 (High Sierra)',
        'czech': 'macOS 10.13 (High Sierra)',
        'danish': 'macOS 10.13 (High Sierra)',
        'dutch': 'macOS 10.13 (High Sierra)',
        'finnish': 'macOS 10.13 (High Sierra)',
        'french': 'macOS 10.13 (High Sierra)',
        'german': 'macOS 10.13 (High Sierra)',
        'greek': 'macOS 10.13 (High Sierra)',
        'hungarian': 'macOS 10.13 (High Sierra)',
        'indonesian': 'macOS 10.13 (High Sierra)',
        'italian': 'macOS 10.13 (High Sierra)',
        'japanese': 'macOS 10.13 (High Sierra)',
        'koreana': 'macOS 10.13 (High Sierra)',
        'latam': 'macOS 10.13 (High Sierra)',
        'malay': 'macOS 10.13 (High Sierra)',
        'norwegian': 'macOS 10.13 (High Sierra)',
        'polish': 'macOS 10.13 (High Sierra)',
        'portuguese': 'macOS 10.13 (High Sierra)',
        'romanian': 'macOS 10.13 (High Sierra)',
        'russian': 'macOS 10.13 (High Sierra)',
        'schinese': 'macOS 10.13 (High Sierra)',
        'spanish': 'macOS 10.13 (High Sierra)',
        'swedish': 'macOS 10.13 (High Sierra)',
        'tchinese': 'macOS 10.13 (High Sierra)',
        'turkish': 'macOS 10.13 (High Sierra)',
        'ukrainian': 'macOS 10.13 (High Sierra)',
        'vietnamese': 'macOS 10.13 (High Sierra)',
    },
    'app[content][sysreqs][mac][min][processor]': {
        'brazilian': 'Apple Silicon, Intel',
        'bulgarian': 'Apple Silicon, Intel',
        'czech': 'Apple Silicon, Intel',
        'danish': 'Apple Silicon, Intel',
        'dutch': 'Apple Silicon, Intel',
        'finnish': 'Apple Silicon, Intel',
        'french': 'Apple Silicon, Intel',
        'german': 'Apple Silicon, Intel',
        'greek': 'Apple Silicon, Intel',
        'hungarian': 'Apple Silicon, Intel',
        'indonesian': 'Apple Silicon, Intel',
        'italian': 'Apple Silicon, Intel',
        'japanese': 'Apple Silicon、Intel',
        'koreana': 'Apple Silicon, Intel',
        'latam': 'Apple Silicon, Intel',
        'malay': 'Apple Silicon, Intel',
        'norwegian': 'Apple Silicon, Intel',
        'polish': 'Apple Silicon, Intel',
        'portuguese': 'Apple Silicon, Intel',
        'romanian': 'Apple Silicon, Intel',
        'russian': 'Apple Silicon, Intel',
        'schinese': 'Apple Silicon, Intel',
        'spanish': 'Apple Silicon, Intel',
        'swedish': 'Apple Silicon, Intel',
        'tchinese': 'Apple Silicon、Intel',
        'turkish': 'Apple Silicon, Intel',
        'ukrainian': 'Apple Silicon, Intel',
        'vietnamese': 'Apple Silicon, Intel',
    },
    'app[content][sysreqs][windows][min][osversion]': {
        'brazilian': 'Windows 10/11',
        'bulgarian': 'Windows 10/11',
        'czech': 'Windows 10/11',
        'danish': 'Windows 10/11',
        'dutch': 'Windows 10/11',
        'finnish': 'Windows 10/11',
        'french': 'Windows 10/11',
        'german': 'Windows 10/11',
        'greek': 'Windows 10/11',
        'hungarian': 'Windows 10/11',
        'indonesian': 'Windows 10/11',
        'italian': 'Windows 10/11',
        'japanese': 'Windows 10/11',
        'koreana': 'Windows 10/11',
        'latam': 'Windows 10/11',
        'malay': 'Windows 10/11',
        'norwegian': 'Windows 10/11',
        'polish': 'Windows 10/11',
        'portuguese': 'Windows 10/11',
        'romanian': 'Windows 10/11',
        'russian': 'Windows 10/11',
        'schinese': 'Windows 10/11',
        'spanish': 'Windows 10/11',
        'swedish': 'Windows 10/11',
        'tchinese': 'Windows 10/11',
        'turkish': 'Windows 10/11',
        'ukrainian': 'Windows 10/11',
        'vietnamese': 'Windows 10/11',
    },
    'app[content][sysreqs][windows][min][processor]': {
        'brazilian': 'CPU dual core',
        'bulgarian': 'Двуядрен процесор',
        'czech': 'Dvoujádrový procesor',
        'danish': 'Dual core-CPU',
        'dutch': 'Dualcore-processor',
        'finnish': 'Kaksiytiminen suoritin',
        'french': 'Processeur double cœur',
        'german': 'Dual-Core-CPU',
        'greek': 'Επεξεργαστής διπλού πυρήνα',
        'hungarian': 'Kétmagos processzor',
        'indonesian': 'CPU dua inti',
        'italian': 'CPU dual core',
        'japanese': 'デュアルコアCPU',
        'koreana': '듀얼 코어 CPU',
        'latam': 'CPU de doble núcleo',
        'malay': 'CPU dwiteras',
        'norwegian': 'Tokjerners CPU',
        'polish': 'Procesor dwurdzeniowy',
        'portuguese': 'CPU dual core',
        'romanian': 'Procesor dual core',
        'russian': 'Двухъядерный процессор',
        'schinese': '双核 CPU',
        'spanish': 'CPU de doble núcleo',
        'swedish': 'Tvåkärnig CPU',
        'tchinese': '雙核心 CPU',
        'turkish': 'Çift çekirdekli işlemci',
        'ukrainian': 'Двоядерний процесор',
        'vietnamese': 'CPU hai nhân',
    },
    'app[content][sysreqs][windows][min][graphics]': {
        'brazilian': 'GPU com aceleração de hardware e suporte a WebGL2 ou WebGPU',
        'bulgarian': 'Видеокарта с хардуерно ускорение и поддръжка на WebGL2 или WebGPU',
        'czech': 'Hardwarově akcelerovaná GPU s podporou WebGL2 nebo WebGPU',
        'danish': 'Hardwareaccelereret GPU med understøttelse af WebGL2 eller WebGPU',
        'dutch': 'Hardwareversnelde GPU met ondersteuning voor WebGL2 of WebGPU',
        'finnish': 'Laitteistokiihdytetty näytönohjain, joka tukee WebGL2:ta tai WebGPU:ta',
        'french': 'GPU à accélération matérielle compatible WebGL2 ou WebGPU',
        'german': 'Hardwarebeschleunigte GPU mit WebGL2- oder WebGPU-Unterstützung',
        'greek': 'Κάρτα γραφικών με επιτάχυνση υλικού και υποστήριξη WebGL2 ή WebGPU',
        'hungarian': 'Hardveresen gyorsított GPU WebGL2 vagy WebGPU támogatással',
        'indonesian': 'GPU dengan akselerasi perangkat keras yang mendukung WebGL2 atau WebGPU',
        'italian': 'GPU con accelerazione hardware compatibile con WebGL2 o WebGPU',
        'japanese': 'WebGL2 または WebGPU に対応したハードウェアアクセラレーション対応GPU',
        'koreana': 'WebGL2 또는 WebGPU를 지원하는 하드웨어 가속 GPU',
        'latam': 'GPU con aceleración por hardware compatible con WebGL2 o WebGPU',
        'malay': 'GPU dengan pecutan perkakasan yang menyokong WebGL2 atau WebGPU',
        'norwegian': 'Maskinvareakselerert GPU med støtte for WebGL2 eller WebGPU',
        'polish': 'Karta graficzna z akceleracją sprzętową i obsługą WebGL2 lub WebGPU',
        'portuguese': 'GPU com aceleração por hardware e suporte a WebGL2 ou WebGPU',
        'romanian': 'Placă video cu accelerare hardware și suport WebGL2 sau WebGPU',
        'russian': 'Видеокарта с аппаратным ускорением и поддержкой WebGL2 или WebGPU',
        'schinese': '支持 WebGL2 或 WebGPU 的硬件加速 GPU',
        'spanish': 'GPU con aceleración por hardware compatible con WebGL2 o WebGPU',
        'swedish': 'Hårdvaruaccelererad GPU med stöd för WebGL2 eller WebGPU',
        'tchinese': '支援 WebGL2 或 WebGPU 的硬體加速 GPU',
        'turkish': 'WebGL2 veya WebGPU destekli, donanım hızlandırmalı ekran kartı',
        'ukrainian': 'Відеокарта з апаратним прискоренням і підтримкою WebGL2 або WebGPU',
        'vietnamese': 'GPU tăng tốc phần cứng có hỗ trợ WebGL2 hoặc WebGPU',
    },
    'app[content][sysreqs][linux][min][osversion]': {
        'brazilian': 'Ubuntu 20.04+',
        'bulgarian': 'Ubuntu 20.04+',
        'czech': 'Ubuntu 20.04+',
        'danish': 'Ubuntu 20.04+',
        'dutch': 'Ubuntu 20.04+',
        'finnish': 'Ubuntu 20.04+',
        'french': 'Ubuntu 20.04+',
        'german': 'Ubuntu 20.04+',
        'greek': 'Ubuntu 20.04+',
        'hungarian': 'Ubuntu 20.04+',
        'indonesian': 'Ubuntu 20.04+',
        'italian': 'Ubuntu 20.04+',
        'japanese': 'Ubuntu 20.04+',
        'koreana': 'Ubuntu 20.04+',
        'latam': 'Ubuntu 20.04+',
        'malay': 'Ubuntu 20.04+',
        'norwegian': 'Ubuntu 20.04+',
        'polish': 'Ubuntu 20.04+',
        'portuguese': 'Ubuntu 20.04+',
        'romanian': 'Ubuntu 20.04+',
        'russian': 'Ubuntu 20.04+',
        'schinese': 'Ubuntu 20.04+',
        'spanish': 'Ubuntu 20.04+',
        'swedish': 'Ubuntu 20.04+',
        'tchinese': 'Ubuntu 20.04+',
        'turkish': 'Ubuntu 20.04+',
        'ukrainian': 'Ubuntu 20.04+',
        'vietnamese': 'Ubuntu 20.04+',
    },
    'app[content][sysreqs][linux][min][processor]': {
        'brazilian': 'CPU dual core',
        'bulgarian': 'Двуядрен процесор',
        'czech': 'Dvoujádrový procesor',
        'danish': 'Dual core-CPU',
        'dutch': 'Dualcore-processor',
        'finnish': 'Kaksiytiminen suoritin',
        'french': 'Processeur double cœur',
        'german': 'Dual-Core-CPU',
        'greek': 'Επεξεργαστής διπλού πυρήνα',
        'hungarian': 'Kétmagos processzor',
        'indonesian': 'CPU dua inti',
        'italian': 'CPU dual core',
        'japanese': 'デュアルコアCPU',
        'koreana': '듀얼 코어 CPU',
        'latam': 'CPU de doble núcleo',
        'malay': 'CPU dwiteras',
        'norwegian': 'Tokjerners CPU',
        'polish': 'Procesor dwurdzeniowy',
        'portuguese': 'CPU dual core',
        'romanian': 'Procesor dual core',
        'russian': 'Двухъядерный процессор',
        'schinese': '双核 CPU',
        'spanish': 'CPU de doble núcleo',
        'swedish': 'Tvåkärnig CPU',
        'tchinese': '雙核心 CPU',
        'turkish': 'Çift çekirdekli işlemci',
        'ukrainian': 'Двоядерний процесор',
        'vietnamese': 'CPU hai nhân',
    },
    'app[content][sysreqs][linux][min][graphics]': {
        'brazilian': 'GPU com aceleração de hardware e suporte a WebGL2 ou WebGPU',
        'bulgarian': 'Видеокарта с хардуерно ускорение и поддръжка на WebGL2 или WebGPU',
        'czech': 'Hardwarově akcelerovaná GPU s podporou WebGL2 nebo WebGPU',
        'danish': 'Hardwareaccelereret GPU med understøttelse af WebGL2 eller WebGPU',
        'dutch': 'Hardwareversnelde GPU met ondersteuning voor WebGL2 of WebGPU',
        'finnish': 'Laitteistokiihdytetty näytönohjain, joka tukee WebGL2:ta tai WebGPU:ta',
        'french': 'GPU à accélération matérielle compatible WebGL2 ou WebGPU',
        'german': 'Hardwarebeschleunigte GPU mit WebGL2- oder WebGPU-Unterstützung',
        'greek': 'Κάρτα γραφικών με επιτάχυνση υλικού και υποστήριξη WebGL2 ή WebGPU',
        'hungarian': 'Hardveresen gyorsított GPU WebGL2 vagy WebGPU támogatással',
        'indonesian': 'GPU dengan akselerasi perangkat keras yang mendukung WebGL2 atau WebGPU',
        'italian': 'GPU con accelerazione hardware compatibile con WebGL2 o WebGPU',
        'japanese': 'WebGL2 または WebGPU に対応したハードウェアアクセラレーション対応GPU',
        'koreana': 'WebGL2 또는 WebGPU를 지원하는 하드웨어 가속 GPU',
        'latam': 'GPU con aceleración por hardware compatible con WebGL2 o WebGPU',
        'malay': 'GPU dengan pecutan perkakasan yang menyokong WebGL2 atau WebGPU',
        'norwegian': 'Maskinvareakselerert GPU med støtte for WebGL2 eller WebGPU',
        'polish': 'Karta graficzna z akceleracją sprzętową i obsługą WebGL2 lub WebGPU',
        'portuguese': 'GPU com aceleração por hardware e suporte a WebGL2 ou WebGPU',
        'romanian': 'Placă video cu accelerare hardware și suport WebGL2 sau WebGPU',
        'russian': 'Видеокарта с аппаратным ускорением и поддержкой WebGL2 или WebGPU',
        'schinese': '支持 WebGL2 或 WebGPU 的硬件加速 GPU',
        'spanish': 'GPU con aceleración por hardware compatible con WebGL2 o WebGPU',
        'swedish': 'Hårdvaruaccelererad GPU med stöd för WebGL2 eller WebGPU',
        'tchinese': '支援 WebGL2 或 WebGPU 的硬體加速 GPU',
        'turkish': 'WebGL2 veya WebGPU destekli, donanım hızlandırmalı ekran kartı',
        'ukrainian': 'Відеокарта з апаратним прискоренням і підтримкою WebGL2 або WebGPU',
        'vietnamese': 'GPU tăng tốc phần cứng có hỗ trợ WebGL2 hoặc WebGPU',
    },
}

SHORT_MAX = 300

data = json.load(open(VDF, encoding='utf-8'))
en = data['languages']['english']

for src, dst in ENGLISH_FIXES:
    if src in en[ABOUT]:
        en[ABOUT] = en[ABOUT].replace(src, dst)
# Every language that has a full set of translated fragments gets written.
# A language is complete only when it appears in every fragment, in SHORT_TEXT
# and in every SYSREQS key, so a half-finished one is skipped rather than
# uploaded with English paragraphs in the middle of it.
def complete_languages():
    have = set(ABOUT_PARTS[0]) - {'english'}
    for frag in ABOUT_PARTS:
        have &= set(frag)
    have &= set(SHORT_TEXT)
    for vals in SYSREQS.values():
        have &= set(vals)
    return sorted(have)

TARGETS = complete_languages()
partial = (set(SHORT_TEXT) | {k for f in ABOUT_PARTS for k in f}) - set(TARGETS) - {'english'}
if partial:
    print(f'incomplete, left untouched: {", ".join(sorted(partial))}')

# BBCode is what the store page is written in, and Steam renders a stray tag
# literally rather than rejecting it. Counting opens against closes per tag
# catches a typo before it reaches the page.
def bbcode_balance(text):
    return {tag: text.count(f'[{tag}]') - text.count(f'[/{tag}]')
            for tag in ('b', 'i', 'h2', 'p', 'list', 'u')}

en_balance = bbcode_balance(en[ABOUT])

# A fragment left identical to the English is almost always one that was
# forgotten, so name them. There are none right now.
untranslated = [(i, lang) for i, frag in enumerate(ABOUT_PARTS)
                for lang in TARGETS if frag[lang] == frag['english']]
if untranslated:
    print('same as english: ' + ', '.join(f'{l} #{i}' for i, l in untranslated))

for lang in TARGETS:
    about = en[ABOUT]
    for frag in ABOUT_PARTS:
        src = frag['english']
        if src not in about:
            sys.exit(f'fragment not found in english about ({lang}): {src[:60]!r}')
        about = about.replace(src, frag[lang], 1)
    block = data['languages'][lang]
    block[ABOUT] = about
    block[SHORT] = SHORT_TEXT[lang]
    for key, vals in SYSREQS.items():
        block[key] = vals[lang]
    if len(block[SHORT]) > SHORT_MAX:
        sys.exit(f'{lang} short_description is {len(block[SHORT])} chars, over {SHORT_MAX}')
    if bbcode_balance(about) != en_balance:
        sys.exit(f'{lang} about has unbalanced BBCode: '
                 f'{bbcode_balance(about)} vs english {en_balance}')

# Match Steam's own export format so a re-download diffs cleanly: compact
# separators, raw UTF-8, and forward slashes escaped the way PHP's json_encode
# writes them. Both forms parse identically; this just keeps the round trip flat.
text = json.dumps(data, ensure_ascii=False, separators=(',', ':')).replace('/', '\\/')
open(VDF, 'w', encoding='utf-8').write(text)
for lang in ['english'] + TARGETS:
    b = data['languages'][lang]
    print(f'{lang:8} about {len(b[ABOUT]):5} chars | short {len(b[SHORT]):3}/{SHORT_MAX}')
